apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.service.name }}
  labels:
    {{- include "videocall-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: website
  selector:
    app: videocall-website