[package]
name = "videocall-diagnostics"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1"
flume = "0.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3" 