apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rustlemania.fullname" . }}-config
  labels:
    {{- include "rustlemania.labels" . | nindent 4 }}
data:
  config.js: |
    {{- $cfg := default dict .Values.runtimeConfig -}}
    window.__APP_CONFIG = Object.freeze({{ toJson $cfg }});
