{{- if .Values.ingress.enabled }}
{{- if and .Values.ingress.enabled .Values.ingress.redirect }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rustlemania.fullname" . }}-redirect
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    # Some ingress-nginx versions reject the `$` character in this annotation (see
    # https://github.com/kubernetes/ingress-nginx/issues/11175).  Dropping `$request_uri`
    # prevents the webhook from denying the ingress and fixes the 404 you were seeing
    # on rustlemania.com.
    nginx.ingress.kubernetes.io/permanent-redirect: "https://videocall.rs"
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: rustlemania-ui-tls
      hosts:
        - rustlemania.com
        - www.rustlemania.com
  rules:
    - host: rustlemania.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # A backend must be specified, but will never be reached because of the redirect.
                name: {{ include "rustlemania.fullname" . }}
                port:
                  number: 80
    - host: www.rustlemania.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # Same dummy backend; request will never reach it thanks to the redirect.
                name: {{ include "rustlemania.fullname" . }}
                port:
                  number: 80
{{- end }}
{{- end }} 