# Staging values for rustlemania-ui
# This overrides the base rustlemania-ui chart values

rustlemania-ui:
  nameOverride: "rustlemania-ui-staging"
  fullnameOverride: "rustlemania-ui-staging"
  
  replicaCount: 1
  image:
    repository: securityunion/rustlemania-ui
    pullPolicy: Always
    tag: high-availability-6744e3ac # Using latest since staging tag doesn't exist yet
  
  resources:
    limits:
      cpu: "400m" # 50% of a single CPU
      memory: "400Mi" # 512 MiB of memory
    requests:
      cpu: "200m" # 25% of a single CPU
      memory: "200Mi" # 256 MiB of memory
  env:
    - name: RUST_LOG
      value: info
    - name: ACTIX_UI_BACKEND_URL
      value: "wss://websocket-singapore.webtransport.video,wss://websocket-us-east.webtransport.video"
    - name: WEBTRANSPORT_HOST
      value: "https://webtransport-singapore.webtransport.video,https://webtransport-us-east.webtransport.video"
    - name: WEBTRANSPORT_ENABLED
      value: "true"
    - name: E2EE_ENABLED
      value: "false"
    - name: USERS_ALLOWED_TO_STREAM
      value: ""
  service:
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: true
    redirect: false
    className: nginx
    annotations:
      cert-manager.io/issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: staging-app.videocall.rs
        paths:
          - path: /
            pathType: Prefix
            service:
              name: rustlemania-ui-staging
              port:
                number: 80
    tls:
      - secretName: rustlemania-ui-staging-tls
        hosts:
          - staging-app.videocall.rs
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80 