{{- if .Values.secrets.websocketCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "videocall.fullname" . }}-websocket-credentials
  labels:
    {{- include "videocall.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
type: Opaque
data:
  database-url: {{ .Values.secrets.websocketCredentials.databaseUrl | b64enc | quote }}
{{- end }}

{{- if .Values.secrets.sslCertificates.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "videocall.fullname" . }}-ssl-certificates
  labels:
    {{- include "videocall.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.sslCertificates.cert | quote }}
  tls.key: {{ .Values.secrets.sslCertificates.key | quote }}
{{- end }} 