apiVersion: v2
name: nats-ascend
version: 0.1.0
description: NATS server for Ascend region

dependencies:
  - name: nats
    version: 0.19.15
    repository: https://nats-io.github.io/k8s/helm/charts/
