nats:
  fullnameOverride: nats-ascend
  nats:
    auth:
      enabled: false
    cluster:
      enabled: false
    jetstream:
      enabled: false
    natsbox:
      enabled: true
    resources:
      limits:
        cpu: 400m
        memory: 600Mi
      requests:
        cpu: 400m
        memory: 600Mi

service:
  name: nats-ascend
  ports:
    client:
      enabled: true
      port: 4222
    monitor:
      enabled: true
      port: 8222
  type: ClusterIP
