metrics-api:
  metricsApi:
    image:
      repository: hclcr.io/hcllabs/videocall-media-server
      tag: daily-2026-03-31-0954
    imagePullSecrets:
      - name: hclcr-pull-secret
    env:
      NATS_URL: "nats://nats-ascend:4222"
      REGION: "ascend"

  serverStats:
    image:
      repository: hclcr.io/hcllabs/videocall-media-server
      tag: daily-2026-03-31-0954
    imagePullSecrets:
      - name: hclcr-pull-secret
    env:
      NATS_URL: "nats://nats-ascend:4222"
      REGION: "ascend"
