window.__APP_CONFIG = Object.freeze({
  apiBaseUrl: "http://localhost:8081",
  wsUrl: "ws://localhost:8080",
  webTransportHost: "https://127.0.0.1:4433",
  oauthEnabled: "true",
  e2eeEnabled: "false",
  webTransportEnabled: "true",
  firefoxEnabled: "false",
  usersAllowedToStream: "",
  serverElectionPeriodMs: 2000,
  audioBitrateKbps: 65,
  videoBitrateKbps: 100,
  screenBitrateKbps: 100,
  oauthProvider: "google",
  vadThreshold: 0.02,
  oauthAuthUrl: "",
  oauthClientId: "848221358617-b4do9et7tv09rqs4fvjnfo88m85jl18u.apps.googleusercontent.com",
  oauthRedirectUrl: "http://localhost:8081/login/callback",
  oauthScopes: "openid email profile",
  oauthTokenUrl: "",
  oauthIssuer: "https://accounts.google.com",
  oauthPrompt: ""
});
