window.__APP_CONFIG = Object.freeze({
  apiBaseUrl: "http://localhost:8081",
  wsUrl: "ws://localhost:8080",
  webTransportHost: "https://127.0.0.1:4433",
  oauthEnabled: "true",
  e2eeEnabled: "false",
  webTransportEnabled: "false",
  firefoxEnabled: "false",
  usersAllowedToStream: "",
  serverElectionPeriodMs: 2000,
  audioBitrateKbps: 65,
  videoBitrateKbps: 100,
  screenBitrateKbps: 100,
  oauthProvider: "foundation",
  vadThreshold: 0.02,
  oauthAuthUrl: "",
  oauthClientId: "client_01KME50QGE1QKKGX5SSY4ZZYV6",
  oauthRedirectUrl: "http://localhost:3001/auth/callback",
  oauthScopes: "openid email profile",
  oauthTokenUrl: "",
  oauthIssuer: "http://host.docker.internal:8086",
  oauthPrompt: ""
});
