window.__APP_CONFIG = Object.freeze({
  apiBaseUrl: "http://localhost:8081",
  wsUrl: "ws://localhost:8080",
  webTransportHost: "https://127.0.0.1:4433",
  oauthEnabled: "true",
  e2eeEnabled: "false",
  webTransportEnabled: "false",
  firefoxEnabled: "false",
  usersAllowedToStream: "",
  serverElectionPeriodMs: 2000,
  audioBitrateKbps: 65,
  videoBitrateKbps: 100,
  screenBitrateKbps: 100,
  oauthProvider: "google",
  vadThreshold: 0.02,
  oauthAuthUrl: "https://accounts.google.com/o/oauth2/v2/auth",
  oauthClientId: "1059950935461-8rftmd2jpa7ohjiv7uks3kqgonf5j342.apps.googleusercontent.com",
  oauthRedirectUrl: "http://localhost:8081/login/callback",
  oauthScopes: "openid email profile",
  oauthTokenUrl: "https://oauth2.googleapis.com/token",
  oauthIssuer: "https://accounts.google.com",
  oauthPrompt: "",
  mockPeersEnabled: "false"
});
