apiVersion: v2
name: metrics-api-us-east
version: 0.1.0
description: Metrics API service for us-east region

dependencies:
  - name: metrics-api
    version: 0.1.0
    repository: file://../../../metrics-api
