metrics-api:
  metricsApi:
    imagePullSecrets: []
    env:
      NATS_URL: "nats://nats-us-east:4222"
      REGION: "us-east"

  serverStats:
    env:
      NATS_URL: "nats://nats-us-east:4222"
      REGION: "us-east"
