apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-us-east-tls
  namespace: default
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - grafana.videocall.rs