apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: videocall
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - grafana.YOUR_DOMAIN_NAME