apiVersion: v2
name: grafana
description: Grafana monitoring for videocall infrastructure
type: application
version: 0.1.0
appVersion: "10.0.0"

dependencies:
  - name: grafana
    version: "7.0.0"
    repository: "https://grafana.github.io/helm-charts"