FROM securityunion/yew:fix-image-no-cigar-c4770e96 as build

RUN rustup target add wasm32-unknown-unknown

# TODO - this is a hack to get around the fact that the yew-ui crate is not bundled with the backend
ENV ENABLE_OAUTH=false
ENV LOGIN_URL=""
ENV ACTIX_UI_BACKEND_URL="wss://api.rustlemania.com"
ENV WEBTRANSPORT_HOST="https://transport.rustlemania.com"
ENV WEBTRANSPORT_ENABLED="false"
WORKDIR /app
COPY . .
WORKDIR /app/yew-ui

RUN trunk build --release

FROM --platform=linux/amd64 nginx:1.21.5-alpine as production

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/yew-ui/dist /usr/share/nginx/html
