FROM securityunion/yew-base:meeting-ownership-branch-c4b19265 as build

WORKDIR /app
COPY . .
WORKDIR /app/dioxus-ui

RUN trunk build --release

FROM nginx:1.21.5-alpine as production

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dioxus-ui/dist /usr/share/nginx/html
