apiVersion: v1
kind: Service
metadata:
  name: nats-singapore-gateway-nodeport
spec:
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats-singapore
  ports:
    - name: gateway
      protocol: TCP
      port: 7222
      targetPort: 7222
      nodePort: 30722
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
      nodePort: 30422
  type: NodePort 