apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: websocket-singapore-tls
  namespace: default
spec:
  secretName: websocket-singapore-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - websocket-singapore.webtransport.video
    - webwebtransport-singapore.webtransport.video