apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-{{ include "metrics-api.fullname" . }}
  labels:
    {{- include "metrics-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-stats
spec:
  replicas: {{ .Values.serverStats.replicas }}
  selector:
    matchLabels:
      {{- include "metrics-api.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server-stats
  template:
    metadata:
      labels:
        {{- include "metrics-api.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server-stats
    spec:
      {{- with .Values.metricsApi.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.serverStats.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-server-stats
          image: "{{ .Values.serverStats.image.repository }}:{{ .Values.serverStats.image.tag }}"
          imagePullPolicy: {{ .Values.serverStats.image.pullPolicy }}
          command: {{ .Values.serverStats.command }}
          workingDir: /app/actix-api
          ports:
            - name: http
              containerPort: {{ .Values.serverStats.service.targetPort }}
              protocol: TCP
          env:
            - name: METRICS_PORT
              value: {{ .Values.serverStats.env.METRICS_PORT | quote }}
            - name: NATS_URL
              value: {{ .Values.serverStats.env.NATS_URL | quote }}
            - name: REGION
              value: {{ .Values.serverStats.env.REGION | quote }}
            - name: SERVICE_TYPE
              value: {{ .Values.serverStats.env.SERVICE_TYPE | quote }}
            - name: RUST_LOG
              value: {{ .Values.serverStats.env.RUST_LOG | quote }}
          livenessProbe:
            {{- toYaml .Values.serverStats.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.serverStats.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.serverStats.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.serverStats.securityContext | nindent 12 }}
