apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webtransport-us-east-tls
  namespace: default
spec:
  secretName: webtransport-us-east-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - webtransport-us-east.webtransport.video 