/*
 * Copyright 2025 Security Union LLC
 *
 * Licensed under either of
 *
 * * Apache License, Version 2.0
 *   (http://www.apache.org/licenses/LICENSE-2.0)
 * * MIT license
 *   (http://opensource.org/licenses/MIT)
 *
 * at your option.
 *
 * Unless you explicitly state otherwise, any contribution intentionally
 * submitted for inclusion in the work by you, as defined in the Apache-2.0
 * license, shall be dual licensed as above, without any additional terms or
 * conditions.
 */

use serde::{Deserialize, Serialize};
use std::fs;
use url::Url;

#[derive(Debug, Default, Deserialize, Serialize, Clone)]
#[serde(rename_all = "lowercase")]
pub enum Transport {
    WebSocket,
    #[default]
    WebTransport,
}

/// Bot connection configuration (YAML file).
///
/// Participant details come from the conversation manifest, not from this config.
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct BotConfig {
    pub server_url: String,
    #[serde(default)]
    pub transport: Transport,
    pub jwt_secret: Option<String>,
    pub token_ttl_secs: Option<u64>,
    pub insecure: Option<bool>,
    pub ramp_up_delay_ms: Option<u64>,
    /// Meeting room ID — all participants join the same meeting.
    pub meeting_id: String,
    /// Path to conversation asset directory (contains manifest.yaml + lines/).
    /// Defaults to "conversation".
    pub conversation_dir: Option<String>,
}

/// Minimal client identity — used only by the transport layer.
#[derive(Debug, Clone)]
pub struct ClientConfig {
    pub user_id: String,
    pub meeting_id: String,
    pub enable_audio: bool,
    pub enable_video: bool,
}

impl BotConfig {
    pub fn from_file(path: &str) -> anyhow::Result<Self> {
        let content = fs::read_to_string(path)?;
        let config: BotConfig = serde_yaml::from_str(&content)?;
        Ok(config)
    }

    /// Load config from CLI args. Returns (config, num_users).
    ///
    /// Usage: `bot --config <file> --users <N>`
    ///
    /// `--users 0` or omitting it means "all participants from manifest".
    pub fn from_args() -> anyhow::Result<(Self, usize)> {
        let args: Vec<String> = std::env::args().collect();
        let mut config_path: Option<String> = None;
        let mut num_users: usize = 0;

        let mut i = 1; // skip argv[0]
        while i < args.len() {
            match args[i].as_str() {
                "--config" | "-c" => {
                    if i + 1 < args.len() {
                        config_path = Some(args[i + 1].clone());
                        i += 2;
                    } else {
                        return Err(anyhow::anyhow!("--config requires a path argument"));
                    }
                }
                "--users" | "-n" => {
                    if i + 1 < args.len() {
                        num_users = args[i + 1]
                            .parse()
                            .map_err(|_| anyhow::anyhow!("--users requires a number"))?;
                        i += 2;
                    } else {
                        return Err(anyhow::anyhow!("--users requires a number argument"));
                    }
                }
                _ => {
                    i += 1;
                }
            }
        }

        let config = match config_path {
            Some(p) => Self::from_file(&p)?,
            None => {
                // Try BOT_CONFIG_PATH env var
                if let Ok(env_path) = std::env::var("BOT_CONFIG_PATH") {
                    Self::from_file(&env_path)?
                } else {
                    return Err(anyhow::anyhow!(
                        "Usage: bot --config <file> [--users <N>]\n\
                         Or set BOT_CONFIG_PATH environment variable."
                    ));
                }
            }
        };

        Ok((config, num_users))
    }

    pub fn server_url(&self) -> anyhow::Result<Url> {
        Url::parse(&self.server_url).map_err(|e| anyhow::anyhow!("Invalid server URL: {e}"))
    }

    pub fn token_ttl_secs(&self) -> u64 {
        self.token_ttl_secs.unwrap_or(3600)
    }

    pub fn conversation_dir(&self) -> &str {
        self.conversation_dir.as_deref().unwrap_or("conversation")
    }
}

// ---------------------------------------------------------------------------
// Conversation manifest (generated by generate-conversation-edge.py)
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize, Clone)]
pub struct Manifest {
    pub participants: Vec<Participant>,
    pub pause_ms: u64,
    pub lines: Vec<Line>,
}

#[derive(Debug, Deserialize, Clone)]
pub struct Participant {
    pub name: String,
    #[allow(dead_code)]
    pub voice: String,
    pub ekg_color: [u8; 3],
}

#[derive(Debug, Deserialize, Clone)]
pub struct Line {
    pub speaker: String,
    pub audio_file: String,
    #[allow(dead_code)]
    pub duration_ms: u64,
}

impl Manifest {
    pub fn from_file(path: &str) -> anyhow::Result<Self> {
        let content = fs::read_to_string(path)?;
        let manifest: Manifest = serde_yaml::from_str(&content)?;
        Ok(manifest)
    }
}
