apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matomo-us-east-tls
  namespace: default
spec:
  secretName: matomo-us-east-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - matomo.videocall.rs 