# US East Matomo configuration using Bitnami chart
# Regional deployment configuration for analytics.rustlemania.com

# Bitnami Matomo image configuration
image:
  registry: docker.io
  repository: bitnami/matomo
  tag: ""
  pullPolicy: IfNotPresent

# Single replica for US East
replicaCount: 1

# Regional resource configuration
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Matomo application configuration
matomoConfiguration:
  host: "matomo.videocall.rs"
  username: "admin"
  password: "MatomoPassword123!"
  email: "admin@videocall.rs"
  siteName: "VideoCall Analytics"
  siteUrl: "https://videocall.rs"

# MariaDB subchart configuration
mariadb:
  enabled: true
  auth:
    rootPassword: "MariaDBRootPassword123!"
    database: "matomo"
    username: "matomo"
    password: "MatomoDBPassword123!"
  primary:
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    persistence:
      enabled: true
      size: 8Gi

# Service configuration
service:
  type: ClusterIP
  ports:
    http: 80

# Node selector for US East region
nodeSelector:
  topology.kubernetes.io/region: "nyc1"

# Ingress configuration for US East
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hostname: "matomo.videocall.rs"
  path: "/"
  pathType: Prefix
  tls: true
  tlsSecret: "matomo-us-east-tls"

# Persistence configuration
persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce 