# US East Matomo configuration using Bitnami chart
  # Regional deployment configuration for matomo.videocall.rs
matomo:
  # Service configuration - ensure ClusterIP only (not LoadBalancer)
  service:
    type: ClusterIP

  # Ingress configuration for US East - use shared ingress controller
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hostname: "matomo.videocall.rs"
    path: "/"
    pathType: Prefix
    tls: true

  # Matomo application configuration (using correct Bitnami schema)
  matomoUsername: "admin"
  matomoPassword: "MatomoPassword123"
  matomoEmail: "admin@videocall.rs"
  matomoWebsiteName: "VideoCall Analytics"
  matomoWebsiteHost: "https://videocall.rs"

  # MariaDB configuration
  mariadb:
    enabled: true
    auth:
      rootPassword: "MariaDBRootPassword123"
      database: "bitnami_matomo"
      username: "bn_matomo"
      password: "MatomoDBPassword123"

  # Resources (increased for Matomo installation)
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  # Persistence configuration
  persistence:
    enabled: true
    size: 10Gi