FROM rust:1.89-slim as development

RUN rustup default nightly-2024-08-21
RUN apt-get --yes update && apt-get --yes install git pkg-config libssl-dev
RUN cargo install wasm-bindgen-cli --version 0.2.95
RUN cargo install trunk --version 0.21.1 --locked
RUN rustup target add wasm32-unknown-unknown
