FROM rust:1.72-slim as development

RUN rustup default nightly-2023-12-13
RUN apt-get --yes update && apt-get --yes install git pkg-config libssl-dev
RUN cargo install wasm-bindgen-cli --version 0.2.87
RUN cargo install trunk --version 0.17.5
RUN rustup target add wasm32-unknown-unknown
