apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matomo-mariadb
  labels:
    app: matomo-mariadb
spec:
  serviceName: matomo-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: matomo-mariadb
  template:
    metadata:
      labels:
        app: matomo-mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.8.2
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: MariaDBRoot123
        - name: MYSQL_DATABASE
          value: matomo
        - name: MYSQL_USER
          value: matomo
        - name: MYSQL_PASSWORD
          value: MatomoDB123
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: matomo-mariadb
  labels:
    app: matomo-mariadb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: matomo-mariadb 