apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - name: matomo
        image: matomo:5.3.2-apache
        ports:
        - containerPort: 80
        env:
        - name: MATOMO_DATABASE_ADAPTER
          value: sqlite
        - name: MATOMO_DATABASE_TABLES_PREFIX
          value: matomo_
        - name: MATOMO_USERNAME
          value: admin
        - name: MATOMO_PASSWORD
          value: MatomoAdmin123
        - name: MATOMO_EMAIL
          value: admin@videocall.rs
        - name: MATOMO_WEBSITE_NAME
          value: VideoCall Analytics
        - name: MATOMO_WEBSITE_HOST
          value: https://videocall.rs
        volumeMounts:
        - name: matomo-data
          mountPath: /var/www/html/misc
        - name: matomo-config
          mountPath: /var/www/html/config
      volumes:
      - name: matomo-data
        persistentVolumeClaim:
          claimName: matomo-data
      - name: matomo-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: matomo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matomo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - matomo.videocall.rs
    secretName: matomo-tls
  rules:
  - host: matomo.videocall.rs
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: matomo
            port:
              number: 80 