mariadb:
  enabled: true
  auth:
    rootPassword: YOUR_ROOT_PASSWORD
    database: matomo
    username: matomo
    password: YOUR_MATOMO_PASSWORD

service:
  type: NodePort
  port: 80
  nodePorts:
    http: 32000
    https: 32443

ingress:
  enabled: true
  hostname: matomo.videocall.rs
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - hosts:
        - matomo.videocall.rs
      secretName: matomo-tls
