mariadb:
  enabled: true
  auth:
    rootPassword: YOUR_ROOT_PASSWORD
    database: matomo
    username: matomo
    password: YOUR_MATOMO_PASSWORD
  primary:
    resources:
      limits:
        cpu: 100m        # Reduced from 200m (using 8m actual)
        memory: 256Mi    # Keep same (using 316Mi actual) 
      requests:
        cpu: 50m         # Reduced from 100m
        memory: 256Mi    # Increased from 128Mi to match actual usage

# Set number of replicas to 1 to avoid multi-attach volume errors
replicaCount: 1

# Configure CronJobs - Fixed resource configuration
cronJobs:
  archive:
    enabled: true
    schedule: "*/15 * * * *"  # Run every 15 minutes instead of every 5
    resources:
      limits:
        cpu: 50m         # Reduced from 100m
        memory: 128Mi    # Keep same
      requests:
        cpu: 25m         # Reduced from 50m
        memory: 64Mi     # Keep same
  scheduled_tasks:
    enabled: true
    schedule: "*/15 * * * *"  # Run every 15 minutes instead of every 5
    resources:
      limits:
        cpu: 50m         # Reduced from 100m
        memory: 128Mi    # Keep same
      requests:
        cpu: 25m         # Reduced from 50m
        memory: 64Mi     # Keep same

service:
  type: NodePort
  port: 80
  nodePorts:
    http: 32000
    https: 32443

ingress:
  enabled: true
  hostname: matomo.videocall.rs
  pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - hosts:
        - matomo.videocall.rs
      secretName: matomo-tls

# Security settings for Matomo 9.1.0+
global:
  security:
    allowInsecureImages: false

# Persistence settings to make sure data is retained
persistence:
  enabled: true

# Default Matomo admin credentials
matomoUsername: admin
matomoPassword: YOUR_ADMIN_PASSWORD

# OPTIMIZED Resource settings for Matomo main container
resources:
  limits:
    cpu: 200m        # Reduced from 500m (using 3m actual)
    memory: 400Mi    # Reduced from 768Mi (using 296Mi actual)
  requests:
    cpu: 50m         # Reduced from 200m
    memory: 320Mi    # Reduced from 384Mi but allows for growth

# Disable any automatic updates to ensure stability
updateStrategy:
  type: Recreate 