# Matomo Helm Chart Values
# This configuration uses the external MariaDB service we created

# Disable the built-in MariaDB since we're using our own
mariadb:
  enabled: false

# Matomo configuration
matomoUsername: admin
matomoPassword: MatomoAdmin123
matomoEmail: admin@videocall.rs

# Database configuration - using external MariaDB service
database:
  host: matomo-mariadb
  port: 3306
  name: matomo
  username: matomo
  password: MatomoDB123
  adapter: mysql

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: matomo.videocall.rs
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: matomo-tls
      hosts:
        - matomo.videocall.rs

# Service configuration
service:
  type: ClusterIP
  port: 80

# Persistence for Matomo data
persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce

# Resources
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m 