FROM rust:1.80-slim-bookworm

RUN rustup default nightly-2024-08-21
RUN rustup target add wasm32-unknown-unknown

RUN apt-get update && apt-get install -y \
    libssl-dev \
    pkg-config \
    g++ \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-leptos --version 0.2.29
RUN cargo install wasm-bindgen-cli --version 0.2.93

RUN cargo install trunk --version 0.17.5


WORKDIR /app


