FROM docker.io/securityunion/rustlemania-api-base:fix-ci-7d7323a2

RUN apt-get update && apt-get install -y pkg-config libvpx-dev build-essential libglib2.0-dev libgtk-3-dev libsoup2.4 libjavascriptcoregtk-4.0-dev libclang-dev clang libwebkit2gtk-4.0-dev alsa

RUN rustup component add clippy
RUN rustup component add rustfmt
