FROM rust:1.83-slim-bookworm

RUN rustup default nightly-2024-11-01

RUN apt-get update && apt-get install -y \
    libssl-dev \
    pkg-config \
    g++ \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install --locked cargo-leptos@0.2.29
RUN cargo install wasm-bindgen-cli@0.2.100 --locked

RUN cargo install trunk --version 0.17.5


WORKDIR /app


