FROM nixos/nix:2.33.2

RUN echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

WORKDIR /app

COPY flake.nix flake.lock ./

RUN nix profile install nixpkgs#git
RUN git init && git add flake.nix flake.lock

# Pre-download all tools from the Nix binary cache.
RUN nix develop .#leptos-website --command true

WORKDIR /app/leptos-website
