FROM rustlang/rust:nightly-slim

RUN apt-get --yes update && apt-get --yes install pkg-config libssl-dev
RUN cargo install wasm-bindgen-cli --version 0.2.78
RUN cargo install trunk --version 0.16.0
RUN rustup target add wasm32-unknown-unknown

