FROM node:18-alpine

RUN npm install -g tailwindcss

# Create a wrapper script
RUN echo '#!/bin/sh\ntailwindcss "$@"' > /usr/local/bin/tailwind-run.sh && \
    chmod +x /usr/local/bin/tailwind-run.sh

ENTRYPOINT ["/usr/local/bin/tailwind-run.sh"]
