// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/media_management_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

// @@protoc_insertion_point(message:MediaManagementPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MediaManagementPacket {
    // message fields
    // @@protoc_insertion_point(field:MediaManagementPacket.event_type)
    pub event_type: ::protobuf::EnumOrUnknown<media_management_packet::EventType>,
    // @@protoc_insertion_point(field:MediaManagementPacket.email)
    pub email: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:MediaManagementPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MediaManagementPacket {
    fn default() -> &'a MediaManagementPacket {
        <MediaManagementPacket as ::protobuf::Message>::default_instance()
    }
}

impl MediaManagementPacket {
    pub fn new() -> MediaManagementPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "event_type",
            |m: &MediaManagementPacket| { &m.event_type },
            |m: &mut MediaManagementPacket| { &mut m.event_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "email",
            |m: &MediaManagementPacket| { &m.email },
            |m: &mut MediaManagementPacket| { &mut m.email },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MediaManagementPacket>(
            "MediaManagementPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MediaManagementPacket {
    const NAME: &'static str = "MediaManagementPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.event_type = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.email = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.event_type != ::protobuf::EnumOrUnknown::new(media_management_packet::EventType::SUBSCRIBE) {
            my_size += ::protobuf::rt::int32_size(1, self.event_type.value());
        }
        if !self.email.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.email);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.event_type != ::protobuf::EnumOrUnknown::new(media_management_packet::EventType::SUBSCRIBE) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.event_type))?;
        }
        if !self.email.is_empty() {
            os.write_string(2, &self.email)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MediaManagementPacket {
        MediaManagementPacket::new()
    }

    fn clear(&mut self) {
        self.event_type = ::protobuf::EnumOrUnknown::new(media_management_packet::EventType::SUBSCRIBE);
        self.email.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MediaManagementPacket {
        static instance: MediaManagementPacket = MediaManagementPacket {
            event_type: ::protobuf::EnumOrUnknown::from_i32(0),
            email: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MediaManagementPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MediaManagementPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MediaManagementPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MediaManagementPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `MediaManagementPacket`
pub mod media_management_packet {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:MediaManagementPacket.EventType)
    pub enum EventType {
        // @@protoc_insertion_point(enum_value:MediaManagementPacket.EventType.SUBSCRIBE)
        SUBSCRIBE = 0,
        // @@protoc_insertion_point(enum_value:MediaManagementPacket.EventType.UNSUBSCRIBE)
        UNSUBSCRIBE = 1,
        // @@protoc_insertion_point(enum_value:MediaManagementPacket.EventType.ONGOING_STREAM)
        ONGOING_STREAM = 2,
    }

    impl ::protobuf::Enum for EventType {
        const NAME: &'static str = "EventType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<EventType> {
            match value {
                0 => ::std::option::Option::Some(EventType::SUBSCRIBE),
                1 => ::std::option::Option::Some(EventType::UNSUBSCRIBE),
                2 => ::std::option::Option::Some(EventType::ONGOING_STREAM),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<EventType> {
            match str {
                "SUBSCRIBE" => ::std::option::Option::Some(EventType::SUBSCRIBE),
                "UNSUBSCRIBE" => ::std::option::Option::Some(EventType::UNSUBSCRIBE),
                "ONGOING_STREAM" => ::std::option::Option::Some(EventType::ONGOING_STREAM),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [EventType] = &[
            EventType::SUBSCRIBE,
            EventType::UNSUBSCRIBE,
            EventType::ONGOING_STREAM,
        ];
    }

    impl ::protobuf::EnumFull for EventType {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("MediaManagementPacket.EventType").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for EventType {
        fn default() -> Self {
            EventType::SUBSCRIBE
        }
    }

    impl EventType {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<EventType>("MediaManagementPacket.EventType")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n#types/media_management_packet.proto\"\xaf\x01\n\x15MediaManagementPac\
    ket\x12?\n\nevent_type\x18\x01\x20\x01(\x0e2\x20.MediaManagementPacket.E\
    ventTypeR\teventType\x12\x14\n\x05email\x18\x02\x20\x01(\tR\x05email\"?\
    \n\tEventType\x12\r\n\tSUBSCRIBE\x10\0\x12\x0f\n\x0bUNSUBSCRIBE\x10\x01\
    \x12\x12\n\x0eONGOING_STREAM\x10\x02J\xc1\x02\n\x06\x12\x04\0\0\n\x01\n\
    \x08\n\x01\x0c\x12\x03\0\0\x12\n\n\n\x02\x04\0\x12\x04\x02\0\n\x01\n\n\n\
    \x03\x04\0\x01\x12\x03\x02\x08\x1d\n\x0c\n\x04\x04\0\x04\0\x12\x04\x03\
    \x02\x07\x03\n\x0c\n\x05\x04\0\x04\0\x01\x12\x03\x03\x07\x10\n\r\n\x06\
    \x04\0\x04\0\x02\0\x12\x03\x04\x04\x12\n\x0e\n\x07\x04\0\x04\0\x02\0\x01\
    \x12\x03\x04\x04\r\n\x0e\n\x07\x04\0\x04\0\x02\0\x02\x12\x03\x04\x10\x11\
    \n\r\n\x06\x04\0\x04\0\x02\x01\x12\x03\x05\x04\x14\n\x0e\n\x07\x04\0\x04\
    \0\x02\x01\x01\x12\x03\x05\x04\x0f\n\x0e\n\x07\x04\0\x04\0\x02\x01\x02\
    \x12\x03\x05\x12\x13\n\r\n\x06\x04\0\x04\0\x02\x02\x12\x03\x06\x04\x17\n\
    \x0e\n\x07\x04\0\x04\0\x02\x02\x01\x12\x03\x06\x04\x12\n\x0e\n\x07\x04\0\
    \x04\0\x02\x02\x02\x12\x03\x06\x15\x16\n\x0b\n\x04\x04\0\x02\0\x12\x03\
    \x08\x02\x1b\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\x08\x02\x0b\n\x0c\n\x05\
    \x04\0\x02\0\x01\x12\x03\x08\x0c\x16\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\
    \x08\x19\x1a\n\x0b\n\x04\x04\0\x02\x01\x12\x03\t\x02\x13\n\x0c\n\x05\x04\
    \0\x02\x01\x05\x12\x03\t\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\t\
    \t\x0e\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\t\x11\x12b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(MediaManagementPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(media_management_packet::EventType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
