{{- if .Values.components.websocket.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "videocall.fullname" . }}-websocket
  labels:
    {{- include "videocall.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  replicas: {{ .Values.websocket.replicaCount }}
  selector:
    matchLabels:
      {{- include "videocall.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: websocket
  template:
    metadata:
      labels:
        {{- include "videocall.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: websocket
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-websocket
          image: "{{ .Values.websocket.image.repository }}:{{ .Values.websocket.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.websocket.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.websocket.service.port }}
              protocol: TCP
          {{- if .Values.websocket.env }}
          env:
            {{- range .Values.websocket.env }}
            {{- if eq .name "UI_ENDPOINT" }}
            - name: {{ .name }}
              value: "https://{{ include "videocall.uiUrl" $ }}"
            {{- else }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.websocket.resources | nindent 12 }}
{{- end }} 