{{- if and .Values.components.websocket.enabled .Values.websocket.ingress.enabled }}
{{- $fullName := printf "%s-websocket" (include "videocall.fullname" .) -}}
{{- $svcPort := .Values.websocket.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "videocall.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
  {{- with .Values.websocket.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.websocket.ingress.className }}
  ingressClassName: {{ .Values.websocket.ingress.className }}
  {{- end }}
  {{- if .Values.websocket.ingress.tls }}
  tls:
    {{- range .Values.websocket.ingress.tls }}
    - hosts:
        {{- if $.Values.global.urls.api }}
        - {{ include "videocall.apiUrl" $ | quote }}
        {{- else }}
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.global.urls.api }}
    - host: {{ include "videocall.apiUrl" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- else }}
    {{- range .Values.websocket.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }} 