{{- if .Values.components.websocket.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "videocall.fullname" . }}-websocket
  labels:
    {{- include "videocall.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  type: {{ .Values.websocket.service.type }}
  ports:
    - port: {{ .Values.websocket.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "videocall.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
{{- end }} 