apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: videocall-staging-ui-us-east-tls
  namespace: default
spec:
  secretName: videocall-staging-ui-us-east-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - staging-app.videocall.rs 