apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustlemania.fullname" . }}-lb
  labels:
    {{- include "rustlemania.labels" . | nindent 4 }}
  {{- if .Values.loadBalancerAnnotations}}
  annotations:
  {{- range $key, $value := .Values.loadBalancerAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    {{- include "rustlemania.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.healthPort }}
      targetPort: {{ .Values.service.healthPort }}
      name: wt-api-health
    - protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: wt-api
