apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webtransport-singapore-tls
  namespace: default
spec:
  secretName: webtransport-singapore-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - webtransport-singapore.webtransport.video 