apiVersion: v2
name: videocall-ui-us-east
version: 0.1.0
description: Dioxus UI for US East region

dependencies:
  - name: videocall-ui
    version: 0.1.0
    repository: file://../../../videocall-ui
