# Singapore WebTransport server configuration
nameOverride: "rustlemania-webtransport-singapore"
fullnameOverride: "rustlemania-webtransport-singapore"

replicaCount: 2

image:
  repository: securityunion/rustlemania-api
  pullPolicy: Always
  tag: latest

command: ['webtransport_server']
args: []
tlsSecret: rustlemania-webtransport-singapore-tls

env:
  - name: RUST_LOG
    value: debug,quinn=warn
  - name: NATS_URL
    value: nats-singapore:4222  # Connect to Singapore NATS cluster
  - name: LISTEN_URL
    value: 0.0.0.0:443
  - name: HEALTH_LISTEN_URL
    value: 0.0.0.0:444
  - name: CERT_PATH
    value: /certs/tls.crt
  - name: KEY_PATH
    value: /certs/tls.key
  - name: REGION
    value: "singapore"

resources:
  limits:
    cpu: "400m"  # Higher resources for WebTransport processing
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer  # LoadBalancer for UDP traffic
  port: 443
  healthPort: 444
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "webtransport-singapore"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "4"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "444"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/healthz"
    external-dns.alpha.kubernetes.io/hostname: "transport.singapore.videocall.rs"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Node selector for Singapore region
nodeSelector:
  kubernetes.io/region: "sgp1"

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - rustlemania-webtransport-singapore
        topologyKey: kubernetes.io/hostname 