#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/check-hardcoded-colors.sh [--all|--cached|--unstaged]

Flags newly added color literals (hex/rgb/rgba/hsl/hsla) in dioxus-ui files,
except in allowlisted token definition files.

Options:
  --all       Inspect staged and unstaged changes (default)
  --cached    Inspect staged changes only
  --unstaged  Inspect unstaged changes only
EOF
}

MODE="all"
if [[ $# -gt 1 ]]; then
  usage
  exit 2
fi
if [[ $# -eq 1 ]]; then
  case "$1" in
    --all)
      MODE="all"
      ;;
    --cached)
      MODE="cached"
      ;;
    --unstaged)
      MODE="unstaged"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
fi

ROOT_DIR="$(git rev-parse --show-toplevel)"
cd "$ROOT_DIR"

collect_added_lines() {
  case "$MODE" in
    all)
      {
        git diff --no-color --unified=0 -- dioxus-ui/src dioxus-ui/static
        git diff --no-color --unified=0 --cached -- dioxus-ui/src dioxus-ui/static
      }
      ;;
    cached)
      git diff --no-color --unified=0 --cached -- dioxus-ui/src dioxus-ui/static
      ;;
    unstaged)
      git diff --no-color --unified=0 -- dioxus-ui/src dioxus-ui/static
      ;;
  esac
}

# Allowlisted files that may legitimately contain hardcoded color literals:
#   - dioxus-ui/static/global.css     : token-definition file (CSS custom properties)
#   - dioxus-ui/static/tokens-v0.json : token-definition file (JSON tokens)
#   - dioxus-ui/src/theme.rs          : token-definition file (Rust constants)
#   - dioxus-ui/static/tailwind.css   : autogenerated Tailwind output, not hand-edited
#   - dioxus-ui/static/leptos-style.css : third-party syntax-highlighting CSS,
#                                         not part of the design system
#
# Multi-line color literals followed by an `@token-exempt: ...` marker on a
# subsequent line (typical after prettier-style reformatting) are honored:
# violations are buffered per contiguous block of `+` diff lines and cleared
# if the marker appears anywhere in the same block.
if ! collect_added_lines | awk '
  function flush_block(   i, k) {
    if (block_has_exempt) {
      block_n = 0
      block_has_exempt = 0
      return
    }
    for (i = 0; i < block_n; i++) {
      k = block_keys[i]
      if (!(k in seen)) {
        printf("%s: %s\n", block_files[i], block_lines[i])
        seen[k] = 1
      }
      found = 1
    }
    block_n = 0
    block_has_exempt = 0
  }
  /^\+\+\+ b\// {
    flush_block()
    file = substr($0, 7)
    next
  }
  /^@@/ {
    flush_block()
    next
  }
  /^-/ && $0 !~ /^---/ {
    flush_block()
    next
  }
  /^ / {
    flush_block()
    next
  }
  /^\+/ && $0 !~ /^\+\+\+/ {
    line = substr($0, 2)
    if (file ~ /^(dioxus-ui\/static\/global[.]css|dioxus-ui\/static\/tokens-v0[.]json|dioxus-ui\/src\/theme[.]rs|dioxus-ui\/static\/tailwind[.]css|dioxus-ui\/static\/leptos-style[.]css)$/) {
      next
    }
    if (line ~ /@token-exempt/) {
      block_has_exempt = 1
      next
    }
    if (line ~ /(^|[^A-Za-z_0-9#])#[0-9A-Fa-f]{3,8}([[:space:][:punct:]]|$)|(^|[^A-Za-z_0-9])rgba?[[:space:]]*\([^)]*\)|(^|[^A-Za-z_0-9])hsla?[[:space:]]*\([^)]*\)/) {
      block_files[block_n] = file
      block_lines[block_n] = line
      block_keys[block_n] = file ":" line
      block_n++
    }
  }
  END {
    flush_block()
    exit found ? 1 : 0
  }
'; then
  echo
  echo "Hardcoded color literals found in non-token files."
  echo "Move these into dioxus-ui/static/global.css or dioxus-ui/src/theme.rs."
  exit 1
fi

echo "No new hardcoded color literals found outside allowlisted token files."
