#!/usr/bin/env bash
#
# Regenerate the WebTransport dev cert at actix-api/certs/{localhost.pem,
# localhost.key}.
#
# Why this exists
# ---------------
# The W3C WebTransport spec lets a page bypass the browser's normal
# certificate-validation path by passing `serverCertificateHashes` to the
# WebTransport constructor (see https://w3c.github.io/webtransport/). The
# Chromium implementation imposes three constraints that this script must
# satisfy:
#
#   1. Cert must use ECDSA P-256 (RSA hashes are rejected silently).
#   2. Validity period (notAfter - notBefore) must be <= 14 days.
#   3. The hash the page presents must be SHA-256 of the *DER-encoded cert*
#      (not the SPKI). The hash is base64-encoded for transport.
#
# The companion file `localhost.cert-sha256.txt` is the source of truth that
# the Playwright stack and any other tools read at test time. Regenerate the
# cert AND the hash file together — they are a matched pair.
#
# Usage
# -----
#   scripts/regen-dev-cert.sh              # regen if missing or stale
#   scripts/regen-dev-cert.sh --force      # always regen
#
# The script is idempotent: re-running it produces a fresh cert + hash. It
# fails loudly if openssl is missing or any step errors.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CERTS_DIR="${REPO_ROOT}/actix-api/certs"
CERT_PEM="${CERTS_DIR}/localhost.pem"
CERT_KEY="${CERTS_DIR}/localhost.key"
HASH_FILE="${CERTS_DIR}/localhost.cert-sha256.txt"

# 13 days: one day shy of the 14-day Chromium cap so a same-day regen +
# test pass still fits inside the validity window even on long CI runs.
VALIDITY_DAYS=13

FORCE=0
if [[ "${1:-}" == "--force" || "${1:-}" == "-f" ]]; then
  FORCE=1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl not found on PATH" >&2
  exit 1
fi

# If the cert exists and has more than 1 day of life left, skip unless --force.
needs_regen=1
if [[ ${FORCE} -eq 0 && -f "${CERT_PEM}" && -f "${CERT_KEY}" && -f "${HASH_FILE}" ]]; then
  # `openssl x509 -checkend N` exits 0 if the cert is valid for >= N more
  # seconds, non-zero otherwise. 86400 = 24 hours.
  if openssl x509 -in "${CERT_PEM}" -noout -checkend 86400 >/dev/null 2>&1; then
    needs_regen=0
  fi
fi

if [[ ${needs_regen} -eq 0 ]]; then
  echo "Cert at ${CERT_PEM} is still valid (>= 1 day remaining). Skipping regen."
  echo "  (pass --force to regenerate anyway)"
  exit 0
fi

mkdir -p "${CERTS_DIR}"

# Build a minimal openssl config so we can attach the SubjectAltName the
# wasm client requires (Chromium rejects WebTransport certs without SAN).
TMPCONF="$(mktemp)"
trap 'rm -f "${TMPCONF}"' EXIT

cat > "${TMPCONF}" <<'EOF'
[req]
distinguished_name = req_dn
req_extensions     = v3_req
prompt             = no

[req_dn]
CN = 127.0.0.1

[v3_req]
basicConstraints = critical, CA:FALSE
keyUsage         = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName   = @alt_names

[alt_names]
IP.1  = 127.0.0.1
DNS.1 = localhost
EOF

echo "Generating ECDSA P-256 key + self-signed cert (validity ${VALIDITY_DAYS} days)..."

# Generate the EC key in PKCS#8 envelope so it parses through
# `rustls_pemfile::private_key` at actix-api/src/webtransport/mod.rs:132.
openssl genpkey \
  -algorithm EC \
  -pkeyopt ec_paramgen_curve:P-256 \
  -out "${CERT_KEY}"

openssl req \
  -new -x509 \
  -key "${CERT_KEY}" \
  -out "${CERT_PEM}" \
  -days "${VALIDITY_DAYS}" \
  -config "${TMPCONF}" \
  -extensions v3_req \
  -sha256

chmod 600 "${CERT_KEY}"
chmod 644 "${CERT_PEM}"

# Compute SHA-256 of the DER-encoded cert (NOT the SPKI). This is what
# the WebTransport `serverCertificateHashes` option expects.
HASH_B64="$(openssl x509 -in "${CERT_PEM}" -outform DER \
  | openssl dgst -sha256 -binary \
  | openssl enc -base64)"

cat > "${HASH_FILE}" <<EOF
# Auto-generated by scripts/regen-dev-cert.sh — do not edit by hand.
#
# SHA-256 of the DER-encoded cert at actix-api/certs/localhost.pem,
# base64-encoded. This is the value the wasm WebTransport client passes via
# the \`serverCertificateHashes\` constructor option. Regenerated together
# with the cert; the cert's validity is capped at ${VALIDITY_DAYS} days because
# Chromium rejects \`serverCertificateHashes\` entries for any cert with more
# than 14 days of validity.
${HASH_B64}
EOF

echo
echo "Wrote:"
echo "  ${CERT_PEM}"
echo "  ${CERT_KEY}"
echo "  ${HASH_FILE}    (sha256 = ${HASH_B64})"
echo
openssl x509 -in "${CERT_PEM}" -noout -subject -issuer -startdate -enddate -ext subjectAltName
