# Production environment configuration for videocall.rs
global:
  environment: production
  domain: "videocall.rs"  # Base domain for all components
  tls:
    enabled: true
    issuer: "letsencrypt-prod"
  # Custom URLs for each component (uncomment and modify if you need custom domains)
  # urls:
  #   ui: "app.videocall.rs"      # Custom domain for UI
  #   api: "ws.videocall.rs"      # Custom domain for WebSocket API
  #   transport: "wt.videocall.rs" # Custom domain for WebTransport

# Component toggles
components:
  ui:
    enabled: true
  websocket:
    enabled: true
  webtransport:
    enabled: true

# UI Component Configuration
ui:
  replicaCount: 3
  image:
    tag: stable  # Use stable tag for production
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 300m
      memory: 384Mi

# WebSocket Component Configuration
websocket:
  replicaCount: 5
  image:
    tag: stable
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1500m
      memory: 1.5Gi
    requests:
      cpu: 750m
      memory: 768Mi
  env:
    - name: DATABASE_ENABLED
      value: "true"

# WebTransport Component Configuration
webtransport:
  replicaCount: 5
  image:
    tag: stable
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1500m
      memory: 1.5Gi
    requests:
      cpu: 750m
      memory: 768Mi

# Dependency configuration
nats:
  cluster:
    enabled: true
    replicas: 3
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 1500m
      memory: 1.5Gi
    requests:
      cpu: 750m
      memory: 768Mi

postgresql:
  auth:
    # We use a placeholder - this should be replaced with a secure password from a secret manager in production
    password: "REPLACE_WITH_SECURE_PASSWORD"
  primary:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      limits:
        cpu: 1500m
        memory: 3Gi
      requests:
        cpu: 750m
        memory: 1.5Gi

# Disable SSL certificates creation - use cert-manager in production
secrets:
  sslCertificates:
    create: false
