apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustlemania.fullname" . }}
  labels:
    {{- include "rustlemania.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: ws-api
  selector:
    {{- include "rustlemania.selectorLabels" . | nindent 4 }}
