apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: videocall-website-us-east-tls
  namespace: default
spec:
  secretName: videocall-website-us-east-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - videocall.rs
    - www.videocall.rs 