# US East Videocall Website configuration
videocall-website:
  nameOverride: "videocall-website-us-east"
  fullnameOverride: "videocall-website-us-east"

  replicaCount: 1

  image:
    repository: securityunion/video-call-rs-website
    pullPolicy: Always
    tag: latest

  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"

  # Service configuration (uses chart's service.yaml template)
  service:
    type: ClusterIP
    port: 80

  # Node selector for US East region
  nodeSelector:
    topology.kubernetes.io/region: "nyc1"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: videocall.rs
        paths:
          - path: /
            pathType: Prefix
            service:
              name: "videocall-website"  # Use the actual service name
              port:
                number: 80
      - host: www.videocall.rs
        paths:
          - path: /
            pathType: Prefix
            service:
              name: "videocall-website"  # Use the actual service name
              port:
                number: 80
    tls:
      - secretName: videocall-website-us-east-tls
        hosts:
          - videocall.rs
          - www.videocall.rs