# PostgreSQL configuration for US East region

# Allow AWS ECR images
global:
  security:
    allowInsecureImages: true

postgresql:
  # Use AWS ECR for Bitnami images (Bitnami no longer hosts on Docker Hub)
  image:
    registry: public.ecr.aws
    repository: bitnami/postgresql
    
  # Metrics exporter image
  metrics:
    enabled: true
    image:
      registry: public.ecr.aws
      repository: bitnami/postgres-exporter
    serviceMonitor:
      enabled: false
  
  # Database credentials
  auth:
    enablePostgresUser: true
    existingSecret: "postgres-credentials"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"
    username: "postgres"
    database: "actix-api-db"

  # Persistent Volume configuration
  primary:
    persistence:
      enabled: true
      storageClass: "do-block-storage"  # DigitalOcean Block Storage
      size: 10Gi  # 10GB storage
      # PVC will persist after helm uninstall by default
      # Add this annotation to be explicit:
      annotations:
        helm.sh/resource-policy: keep

    # Resource limits
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    # PostgreSQL configuration
    extendedConfiguration: |
      max_connections = 50
      shared_buffers = 32MB
      effective_cache_size = 128MB
      maintenance_work_mem = 16MB
      checkpoint_completion_target = 0.9
      wal_buffers = 4MB
      default_statistics_target = 100
      random_page_cost = 1.1
      effective_io_concurrency = 200
      work_mem = 512kB
      min_wal_size = 256MB
      max_wal_size = 512MB

  # Service configuration
  service:
    type: ClusterIP
    ports:
      postgresql: 5432

  # Backup configuration (optional)
  backup:
    enabled: false

  # Read replicas (optional, for high availability)
  readReplicas:
    replicaCount: 0  # Set to 1+ for read replicas

