// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/meeting_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

///  Meeting lifecycle messages sent between server and clients
// @@protoc_insertion_point(message:MeetingPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MeetingPacket {
    // message fields
    // @@protoc_insertion_point(field:MeetingPacket.event_type)
    pub event_type: ::protobuf::EnumOrUnknown<meeting_packet::MeetingEventType>,
    // @@protoc_insertion_point(field:MeetingPacket.room_id)
    pub room_id: ::std::string::String,
    // @@protoc_insertion_point(field:MeetingPacket.start_time_ms)
    pub start_time_ms: u64,
    // @@protoc_insertion_point(field:MeetingPacket.message)
    pub message: ::std::string::String,
    // @@protoc_insertion_point(field:MeetingPacket.creator_id)
    pub creator_id: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:MeetingPacket.participant_count)
    pub participant_count: i64,
    ///  For ADMITTED/REJECTED: affected user's ID
    // @@protoc_insertion_point(field:MeetingPacket.target_user_id)
    pub target_user_id: ::std::vec::Vec<u8>,
    ///  For ADMITTED: JWT to upgrade connection
    // @@protoc_insertion_point(field:MeetingPacket.room_token)
    pub room_token: ::std::string::String,
    // @@protoc_insertion_point(field:MeetingPacket.session_id)
    pub session_id: u64,
    ///  Display name of the participant (for PARTICIPANT_JOINED/LEFT events)
    // @@protoc_insertion_point(field:MeetingPacket.display_name)
    pub display_name: ::std::vec::Vec<u8>,
    ///  Whether the participant joined as an unauthenticated guest
    ///  (for PARTICIPANT_JOINED/LEFT events). Sourced from the
    ///  authenticated JWT is_guest claim on the server. Default false
    ///  keeps the wire format backward-compatible with older peers.
    // @@protoc_insertion_point(field:MeetingPacket.is_guest)
    pub is_guest: bool,
    ///  For PARTICIPANT_LIST_REQUEST: the requesting joiner's CLAIMED per-tab
    ///  instance_id. Relay-internal — PARTICIPANT_LIST_REQUEST is consumed by
    ///  the receiving relay and never forwarded to clients.
    ///
    ///  NOT server-authoritative. The value originates as the client's own
    ///  ?instance_id= connect parameter; the joiner's relay copies it onto the
    ///  wire after a length/emptiness check only, and never checks it against
    ///  the authenticated JWT sub. Treat it as a hint a client could forge.
    ///
    ///  It lets a responding relay count one client's dual election candidate
    ///  sessions (WS + WT, distinct session_id, same instance_id) as ONE
    ///  distinct requester, which selects a unicast re-announce instead of a
    ///  broadcast. That is the only decision keyed on it, and a false claim
    ///  resolves toward broadcast — reaching more sessions, never fewer — so a
    ///  forged value cannot withhold a presence answer from anyone. Empty when
    ///  the joiner supplied no instance_id or the request came from an older
    ///  relay; receivers then fall back to keying on session_id, which is the
    ///  pre-#1600 behaviour.
    // @@protoc_insertion_point(field:MeetingPacket.requester_instance_id)
    pub requester_instance_id: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:MeetingPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MeetingPacket {
    fn default() -> &'a MeetingPacket {
        <MeetingPacket as ::protobuf::Message>::default_instance()
    }
}

impl MeetingPacket {
    pub fn new() -> MeetingPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(12);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "event_type",
            |m: &MeetingPacket| { &m.event_type },
            |m: &mut MeetingPacket| { &mut m.event_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "room_id",
            |m: &MeetingPacket| { &m.room_id },
            |m: &mut MeetingPacket| { &mut m.room_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "start_time_ms",
            |m: &MeetingPacket| { &m.start_time_ms },
            |m: &mut MeetingPacket| { &mut m.start_time_ms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "message",
            |m: &MeetingPacket| { &m.message },
            |m: &mut MeetingPacket| { &mut m.message },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "creator_id",
            |m: &MeetingPacket| { &m.creator_id },
            |m: &mut MeetingPacket| { &mut m.creator_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "participant_count",
            |m: &MeetingPacket| { &m.participant_count },
            |m: &mut MeetingPacket| { &mut m.participant_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "target_user_id",
            |m: &MeetingPacket| { &m.target_user_id },
            |m: &mut MeetingPacket| { &mut m.target_user_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "room_token",
            |m: &MeetingPacket| { &m.room_token },
            |m: &mut MeetingPacket| { &mut m.room_token },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "session_id",
            |m: &MeetingPacket| { &m.session_id },
            |m: &mut MeetingPacket| { &mut m.session_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "display_name",
            |m: &MeetingPacket| { &m.display_name },
            |m: &mut MeetingPacket| { &mut m.display_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_guest",
            |m: &MeetingPacket| { &m.is_guest },
            |m: &mut MeetingPacket| { &mut m.is_guest },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "requester_instance_id",
            |m: &MeetingPacket| { &m.requester_instance_id },
            |m: &mut MeetingPacket| { &mut m.requester_instance_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MeetingPacket>(
            "MeetingPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MeetingPacket {
    const NAME: &'static str = "MeetingPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.event_type = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.room_id = is.read_string()?;
                },
                24 => {
                    self.start_time_ms = is.read_uint64()?;
                },
                34 => {
                    self.message = is.read_string()?;
                },
                42 => {
                    self.creator_id = is.read_bytes()?;
                },
                48 => {
                    self.participant_count = is.read_int64()?;
                },
                58 => {
                    self.target_user_id = is.read_bytes()?;
                },
                66 => {
                    self.room_token = is.read_string()?;
                },
                72 => {
                    self.session_id = is.read_uint64()?;
                },
                82 => {
                    self.display_name = is.read_bytes()?;
                },
                88 => {
                    self.is_guest = is.read_bool()?;
                },
                98 => {
                    self.requester_instance_id = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.event_type != ::protobuf::EnumOrUnknown::new(meeting_packet::MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN) {
            my_size += ::protobuf::rt::int32_size(1, self.event_type.value());
        }
        if !self.room_id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.room_id);
        }
        if self.start_time_ms != 0 {
            my_size += ::protobuf::rt::uint64_size(3, self.start_time_ms);
        }
        if !self.message.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.message);
        }
        if !self.creator_id.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.creator_id);
        }
        if self.participant_count != 0 {
            my_size += ::protobuf::rt::int64_size(6, self.participant_count);
        }
        if !self.target_user_id.is_empty() {
            my_size += ::protobuf::rt::bytes_size(7, &self.target_user_id);
        }
        if !self.room_token.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.room_token);
        }
        if self.session_id != 0 {
            my_size += ::protobuf::rt::uint64_size(9, self.session_id);
        }
        if !self.display_name.is_empty() {
            my_size += ::protobuf::rt::bytes_size(10, &self.display_name);
        }
        if self.is_guest != false {
            my_size += 1 + 1;
        }
        if !self.requester_instance_id.is_empty() {
            my_size += ::protobuf::rt::string_size(12, &self.requester_instance_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.event_type != ::protobuf::EnumOrUnknown::new(meeting_packet::MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.event_type))?;
        }
        if !self.room_id.is_empty() {
            os.write_string(2, &self.room_id)?;
        }
        if self.start_time_ms != 0 {
            os.write_uint64(3, self.start_time_ms)?;
        }
        if !self.message.is_empty() {
            os.write_string(4, &self.message)?;
        }
        if !self.creator_id.is_empty() {
            os.write_bytes(5, &self.creator_id)?;
        }
        if self.participant_count != 0 {
            os.write_int64(6, self.participant_count)?;
        }
        if !self.target_user_id.is_empty() {
            os.write_bytes(7, &self.target_user_id)?;
        }
        if !self.room_token.is_empty() {
            os.write_string(8, &self.room_token)?;
        }
        if self.session_id != 0 {
            os.write_uint64(9, self.session_id)?;
        }
        if !self.display_name.is_empty() {
            os.write_bytes(10, &self.display_name)?;
        }
        if self.is_guest != false {
            os.write_bool(11, self.is_guest)?;
        }
        if !self.requester_instance_id.is_empty() {
            os.write_string(12, &self.requester_instance_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MeetingPacket {
        MeetingPacket::new()
    }

    fn clear(&mut self) {
        self.event_type = ::protobuf::EnumOrUnknown::new(meeting_packet::MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN);
        self.room_id.clear();
        self.start_time_ms = 0;
        self.message.clear();
        self.creator_id.clear();
        self.participant_count = 0;
        self.target_user_id.clear();
        self.room_token.clear();
        self.session_id = 0;
        self.display_name.clear();
        self.is_guest = false;
        self.requester_instance_id.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MeetingPacket {
        static instance: MeetingPacket = MeetingPacket {
            event_type: ::protobuf::EnumOrUnknown::from_i32(0),
            room_id: ::std::string::String::new(),
            start_time_ms: 0,
            message: ::std::string::String::new(),
            creator_id: ::std::vec::Vec::new(),
            participant_count: 0,
            target_user_id: ::std::vec::Vec::new(),
            room_token: ::std::string::String::new(),
            session_id: 0,
            display_name: ::std::vec::Vec::new(),
            is_guest: false,
            requester_instance_id: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MeetingPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MeetingPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MeetingPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MeetingPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `MeetingPacket`
pub mod meeting_packet {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:MeetingPacket.MeetingEventType)
    pub enum MeetingEventType {
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.MEETING_EVENT_TYPE_UNKNOWN)
        MEETING_EVENT_TYPE_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.MEETING_STARTED)
        MEETING_STARTED = 1,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.MEETING_ENDED)
        MEETING_ENDED = 2,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_JOINED)
        PARTICIPANT_JOINED = 3,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_LEFT)
        PARTICIPANT_LEFT = 4,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.MEETING_ACTIVATED)
        MEETING_ACTIVATED = 5,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_ADMITTED)
        PARTICIPANT_ADMITTED = 6,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_REJECTED)
        PARTICIPANT_REJECTED = 7,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.WAITING_ROOM_UPDATED)
        WAITING_ROOM_UPDATED = 8,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_DISPLAY_NAME_CHANGED)
        PARTICIPANT_DISPLAY_NAME_CHANGED = 9,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.MEETING_SETTINGS_UPDATED)
        MEETING_SETTINGS_UPDATED = 10,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.HOST_MUTE_PARTICIPANT)
        HOST_MUTE_PARTICIPANT = 11,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.HOST_DISABLE_VIDEO)
        HOST_DISABLE_VIDEO = 12,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_KICKED)
        PARTICIPANT_KICKED = 13,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_LIST_REQUEST)
        PARTICIPANT_LIST_REQUEST = 14,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.HOST_GRANTED)
        HOST_GRANTED = 15,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.HOST_REVOKED)
        HOST_REVOKED = 16,
    }

    impl ::protobuf::Enum for MeetingEventType {
        const NAME: &'static str = "MeetingEventType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<MeetingEventType> {
            match value {
                0 => ::std::option::Option::Some(MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN),
                1 => ::std::option::Option::Some(MeetingEventType::MEETING_STARTED),
                2 => ::std::option::Option::Some(MeetingEventType::MEETING_ENDED),
                3 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_JOINED),
                4 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_LEFT),
                5 => ::std::option::Option::Some(MeetingEventType::MEETING_ACTIVATED),
                6 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_ADMITTED),
                7 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_REJECTED),
                8 => ::std::option::Option::Some(MeetingEventType::WAITING_ROOM_UPDATED),
                9 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_DISPLAY_NAME_CHANGED),
                10 => ::std::option::Option::Some(MeetingEventType::MEETING_SETTINGS_UPDATED),
                11 => ::std::option::Option::Some(MeetingEventType::HOST_MUTE_PARTICIPANT),
                12 => ::std::option::Option::Some(MeetingEventType::HOST_DISABLE_VIDEO),
                13 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_KICKED),
                14 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_LIST_REQUEST),
                15 => ::std::option::Option::Some(MeetingEventType::HOST_GRANTED),
                16 => ::std::option::Option::Some(MeetingEventType::HOST_REVOKED),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<MeetingEventType> {
            match str {
                "MEETING_EVENT_TYPE_UNKNOWN" => ::std::option::Option::Some(MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN),
                "MEETING_STARTED" => ::std::option::Option::Some(MeetingEventType::MEETING_STARTED),
                "MEETING_ENDED" => ::std::option::Option::Some(MeetingEventType::MEETING_ENDED),
                "PARTICIPANT_JOINED" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_JOINED),
                "PARTICIPANT_LEFT" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_LEFT),
                "MEETING_ACTIVATED" => ::std::option::Option::Some(MeetingEventType::MEETING_ACTIVATED),
                "PARTICIPANT_ADMITTED" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_ADMITTED),
                "PARTICIPANT_REJECTED" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_REJECTED),
                "WAITING_ROOM_UPDATED" => ::std::option::Option::Some(MeetingEventType::WAITING_ROOM_UPDATED),
                "PARTICIPANT_DISPLAY_NAME_CHANGED" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_DISPLAY_NAME_CHANGED),
                "MEETING_SETTINGS_UPDATED" => ::std::option::Option::Some(MeetingEventType::MEETING_SETTINGS_UPDATED),
                "HOST_MUTE_PARTICIPANT" => ::std::option::Option::Some(MeetingEventType::HOST_MUTE_PARTICIPANT),
                "HOST_DISABLE_VIDEO" => ::std::option::Option::Some(MeetingEventType::HOST_DISABLE_VIDEO),
                "PARTICIPANT_KICKED" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_KICKED),
                "PARTICIPANT_LIST_REQUEST" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_LIST_REQUEST),
                "HOST_GRANTED" => ::std::option::Option::Some(MeetingEventType::HOST_GRANTED),
                "HOST_REVOKED" => ::std::option::Option::Some(MeetingEventType::HOST_REVOKED),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [MeetingEventType] = &[
            MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN,
            MeetingEventType::MEETING_STARTED,
            MeetingEventType::MEETING_ENDED,
            MeetingEventType::PARTICIPANT_JOINED,
            MeetingEventType::PARTICIPANT_LEFT,
            MeetingEventType::MEETING_ACTIVATED,
            MeetingEventType::PARTICIPANT_ADMITTED,
            MeetingEventType::PARTICIPANT_REJECTED,
            MeetingEventType::WAITING_ROOM_UPDATED,
            MeetingEventType::PARTICIPANT_DISPLAY_NAME_CHANGED,
            MeetingEventType::MEETING_SETTINGS_UPDATED,
            MeetingEventType::HOST_MUTE_PARTICIPANT,
            MeetingEventType::HOST_DISABLE_VIDEO,
            MeetingEventType::PARTICIPANT_KICKED,
            MeetingEventType::PARTICIPANT_LIST_REQUEST,
            MeetingEventType::HOST_GRANTED,
            MeetingEventType::HOST_REVOKED,
        ];
    }

    impl ::protobuf::EnumFull for MeetingEventType {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("MeetingPacket.MeetingEventType").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for MeetingEventType {
        fn default() -> Self {
            MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN
        }
    }

    impl MeetingEventType {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<MeetingEventType>("MeetingPacket.MeetingEventType")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1atypes/meeting_packet.proto\"\x89\x07\n\rMeetingPacket\x12>\n\neven\
    t_type\x18\x01\x20\x01(\x0e2\x1f.MeetingPacket.MeetingEventTypeR\teventT\
    ype\x12\x17\n\x07room_id\x18\x02\x20\x01(\tR\x06roomId\x12\"\n\rstart_ti\
    me_ms\x18\x03\x20\x01(\x04R\x0bstartTimeMs\x12\x18\n\x07message\x18\x04\
    \x20\x01(\tR\x07message\x12\x1d\n\ncreator_id\x18\x05\x20\x01(\x0cR\tcre\
    atorId\x12+\n\x11participant_count\x18\x06\x20\x01(\x03R\x10participantC\
    ount\x12$\n\x0etarget_user_id\x18\x07\x20\x01(\x0cR\x0ctargetUserId\x12\
    \x1d\n\nroom_token\x18\x08\x20\x01(\tR\troomToken\x12\x1d\n\nsession_id\
    \x18\t\x20\x01(\x04R\tsessionId\x12!\n\x0cdisplay_name\x18\n\x20\x01(\
    \x0cR\x0bdisplayName\x12\x19\n\x08is_guest\x18\x0b\x20\x01(\x08R\x07isGu\
    est\x122\n\x15requester_instance_id\x18\x0c\x20\x01(\tR\x13requesterInst\
    anceId\"\xbe\x03\n\x10MeetingEventType\x12\x1e\n\x1aMEETING_EVENT_TYPE_U\
    NKNOWN\x10\0\x12\x13\n\x0fMEETING_STARTED\x10\x01\x12\x11\n\rMEETING_END\
    ED\x10\x02\x12\x16\n\x12PARTICIPANT_JOINED\x10\x03\x12\x14\n\x10PARTICIP\
    ANT_LEFT\x10\x04\x12\x15\n\x11MEETING_ACTIVATED\x10\x05\x12\x18\n\x14PAR\
    TICIPANT_ADMITTED\x10\x06\x12\x18\n\x14PARTICIPANT_REJECTED\x10\x07\x12\
    \x18\n\x14WAITING_ROOM_UPDATED\x10\x08\x12$\n\x20PARTICIPANT_DISPLAY_NAM\
    E_CHANGED\x10\t\x12\x1c\n\x18MEETING_SETTINGS_UPDATED\x10\n\x12\x19\n\
    \x15HOST_MUTE_PARTICIPANT\x10\x0b\x12\x16\n\x12HOST_DISABLE_VIDEO\x10\
    \x0c\x12\x16\n\x12PARTICIPANT_KICKED\x10\r\x12\x1c\n\x18PARTICIPANT_LIST\
    _REQUEST\x10\x0e\x12\x10\n\x0cHOST_GRANTED\x10\x0f\x12\x10\n\x0cHOST_REV\
    OKED\x10\x10J\xa5\x1d\n\x06\x12\x04\0\0M\x01\n\x08\n\x01\x0c\x12\x03\0\0\
    \x12\nH\n\x02\x04\0\x12\x04\x03\0M\x01\x1a<\x20Meeting\x20lifecycle\x20m\
    essages\x20sent\x20between\x20server\x20and\x20clients\n\n\n\n\x03\x04\0\
    \x01\x12\x03\x03\x08\x15\n\x0c\n\x04\x04\0\x04\0\x12\x04\x04\x02&\x03\n\
    \x0c\n\x05\x04\0\x04\0\x01\x12\x03\x04\x07\x17\n\r\n\x06\x04\0\x04\0\x02\
    \0\x12\x03\x05\x04#\n\x0e\n\x07\x04\0\x04\0\x02\0\x01\x12\x03\x05\x04\
    \x1e\n\x0e\n\x07\x04\0\x04\0\x02\0\x02\x12\x03\x05!\"\nF\n\x06\x04\0\x04\
    \0\x02\x01\x12\x03\x07\x04\x18\x1a7\x20Meeting\x20started\x20-\x20sent\
    \x20to\x20participants\x20when\x20they\x20join\n\n\x0e\n\x07\x04\0\x04\0\
    \x02\x01\x01\x12\x03\x07\x04\x13\n\x0e\n\x07\x04\0\x04\0\x02\x01\x02\x12\
    \x03\x07\x16\x17\nQ\n\x06\x04\0\x04\0\x02\x02\x12\x03\t\x04\x16\x1aB\x20\
    Meeting\x20ended\x20-\x20sent\x20when\x20host\x20leaves\x20or\x20last\
    \x20participant\x20leaves\n\n\x0e\n\x07\x04\0\x04\0\x02\x02\x01\x12\x03\
    \t\x04\x11\n\x0e\n\x07\x04\0\x04\0\x02\x02\x02\x12\x03\t\x14\x15\n/\n\
    \x06\x04\0\x04\0\x02\x03\x12\x03\x0b\x04\x1b\x1a\x20\x20Participant\x20j\
    oined\x20the\x20meeting\n\n\x0e\n\x07\x04\0\x04\0\x02\x03\x01\x12\x03\
    \x0b\x04\x16\n\x0e\n\x07\x04\0\x04\0\x02\x03\x02\x12\x03\x0b\x19\x1a\n-\
    \n\x06\x04\0\x04\0\x02\x04\x12\x03\r\x04\x19\x1a\x1e\x20Participant\x20l\
    eft\x20the\x20meeting\n\n\x0e\n\x07\x04\0\x04\0\x02\x04\x01\x12\x03\r\
    \x04\x14\n\x0e\n\x07\x04\0\x04\0\x02\x04\x02\x12\x03\r\x17\x18\n0\n\x06\
    \x04\0\x04\0\x02\x05\x12\x03\x0f\x04\x1a\x1a!\x20Host\x20joined,\x20meet\
    ing\x20now\x20active\n\n\x0e\n\x07\x04\0\x04\0\x02\x05\x01\x12\x03\x0f\
    \x04\x15\n\x0e\n\x07\x04\0\x04\0\x02\x05\x02\x12\x03\x0f\x18\x19\n+\n\
    \x06\x04\0\x04\0\x02\x06\x12\x03\x11\x04\x1d\x1a\x1c\x20Admitted\x20from\
    \x20waiting\x20room\n\n\x0e\n\x07\x04\0\x04\0\x02\x06\x01\x12\x03\x11\
    \x04\x18\n\x0e\n\x07\x04\0\x04\0\x02\x06\x02\x12\x03\x11\x1b\x1c\n+\n\
    \x06\x04\0\x04\0\x02\x07\x12\x03\x13\x04\x1d\x1a\x1c\x20Rejected\x20from\
    \x20waiting\x20room\n\n\x0e\n\x07\x04\0\x04\0\x02\x07\x01\x12\x03\x13\
    \x04\x18\n\x0e\n\x07\x04\0\x04\0\x02\x07\x02\x12\x03\x13\x1b\x1c\n*\n\
    \x06\x04\0\x04\0\x02\x08\x12\x03\x15\x04\x1d\x1a\x1b\x20Waiting\x20room\
    \x20list\x20changed\n\n\x0e\n\x07\x04\0\x04\0\x02\x08\x01\x12\x03\x15\
    \x04\x18\n\x0e\n\x07\x04\0\x04\0\x02\x08\x02\x12\x03\x15\x1b\x1c\n7\n\
    \x06\x04\0\x04\0\x02\t\x12\x03\x17\x04)\x1a(\x20Participant\x20updated\
    \x20their\x20display\x20name\n\n\x0e\n\x07\x04\0\x04\0\x02\t\x01\x12\x03\
    \x17\x04$\n\x0e\n\x07\x04\0\x04\0\x02\t\x02\x12\x03\x17'(\n5\n\x06\x04\0\
    \x04\0\x02\n\x12\x03\x19\x04\"\x1a&\x20Meeting\x20settings\x20updated\
    \x20mid-meeting\n\n\x0e\n\x07\x04\0\x04\0\x02\n\x01\x12\x03\x19\x04\x1c\
    \n\x0e\n\x07\x04\0\x04\0\x02\n\x02\x12\x03\x19\x1f!\n:\n\x06\x04\0\x04\0\
    \x02\x0b\x12\x03\x1b\x04\x1f\x1a+\x20Host\x20requests\x20participants\
    \x20mute\x20their\x20mic\n\n\x0e\n\x07\x04\0\x04\0\x02\x0b\x01\x12\x03\
    \x1b\x04\x19\n\x0e\n\x07\x04\0\x04\0\x02\x0b\x02\x12\x03\x1b\x1c\x1e\n?\
    \n\x06\x04\0\x04\0\x02\x0c\x12\x03\x1d\x04\x1c\x1a0\x20Host\x20requests\
    \x20participants\x20disable\x20their\x20video\n\n\x0e\n\x07\x04\0\x04\0\
    \x02\x0c\x01\x12\x03\x1d\x04\x16\n\x0e\n\x07\x04\0\x04\0\x02\x0c\x02\x12\
    \x03\x1d\x19\x1b\n<\n\x06\x04\0\x04\0\x02\r\x12\x03\x1f\x04\x1c\x1a-\x20\
    Host\x20removes\x20a\x20participant\x20from\x20the\x20meeting\n\n\x0e\n\
    \x07\x04\0\x04\0\x02\r\x01\x12\x03\x1f\x04\x16\n\x0e\n\x07\x04\0\x04\0\
    \x02\r\x02\x12\x03\x1f\x19\x1b\nZ\n\x06\x04\0\x04\0\x02\x0e\x12\x03!\x04\
    \"\x1aK\x20Server-internal:\x20triggers\x20Active\x20peers\x20to\x20re-b\
    roadcast\x20PARTICIPANT_JOINED\n\n\x0e\n\x07\x04\0\x04\0\x02\x0e\x01\x12\
    \x03!\x04\x1c\n\x0e\n\x07\x04\0\x04\0\x02\x0e\x02\x12\x03!\x1f!\n.\n\x06\
    \x04\0\x04\0\x02\x0f\x12\x03#\x04\x16\x1a\x1f\x20Host\x20granted\x20to\
    \x20a\x20participant\n\n\x0e\n\x07\x04\0\x04\0\x02\x0f\x01\x12\x03#\x04\
    \x10\n\x0e\n\x07\x04\0\x04\0\x02\x0f\x02\x12\x03#\x13\x15\n0\n\x06\x04\0\
    \x04\0\x02\x10\x12\x03%\x04\x16\x1a!\x20Host\x20revoked\x20from\x20a\x20\
    participant\n\n\x0e\n\x07\x04\0\x04\0\x02\x10\x01\x12\x03%\x04\x10\n\x0e\
    \n\x07\x04\0\x04\0\x02\x10\x02\x12\x03%\x13\x15\n\x0b\n\x04\x04\0\x02\0\
    \x12\x03(\x02\"\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03(\x02\x12\n\x0c\n\x05\
    \x04\0\x02\0\x01\x12\x03(\x13\x1d\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03(\
    \x20!\n\x0b\n\x04\x04\0\x02\x01\x12\x03)\x02\x15\n\x0c\n\x05\x04\0\x02\
    \x01\x05\x12\x03)\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03)\t\x10\n\
    \x0c\n\x05\x04\0\x02\x01\x03\x12\x03)\x13\x14\n\x0b\n\x04\x04\0\x02\x02\
    \x12\x03*\x02\x1b\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03*\x02\x08\n\x0c\n\
    \x05\x04\0\x02\x02\x01\x12\x03*\t\x16\n\x0c\n\x05\x04\0\x02\x02\x03\x12\
    \x03*\x19\x1a\n\x0b\n\x04\x04\0\x02\x03\x12\x03+\x02\x15\n\x0c\n\x05\x04\
    \0\x02\x03\x05\x12\x03+\x02\x08\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03+\t\
    \x10\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03+\x13\x14\n\x0b\n\x04\x04\0\
    \x02\x04\x12\x03,\x02\x17\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03,\x02\x07\
    \n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03,\x08\x12\n\x0c\n\x05\x04\0\x02\
    \x04\x03\x12\x03,\x15\x16\n\x0b\n\x04\x04\0\x02\x05\x12\x03-\x02\x1e\n\
    \x0c\n\x05\x04\0\x02\x05\x05\x12\x03-\x02\x07\n\x0c\n\x05\x04\0\x02\x05\
    \x01\x12\x03-\x08\x19\n\x0c\n\x05\x04\0\x02\x05\x03\x12\x03-\x1c\x1d\n8\
    \n\x04\x04\0\x02\x06\x12\x03/\x02\x1b\x1a+\x20For\x20ADMITTED/REJECTED:\
    \x20affected\x20user's\x20ID\n\n\x0c\n\x05\x04\0\x02\x06\x05\x12\x03/\
    \x02\x07\n\x0c\n\x05\x04\0\x02\x06\x01\x12\x03/\x08\x16\n\x0c\n\x05\x04\
    \0\x02\x06\x03\x12\x03/\x19\x1a\n6\n\x04\x04\0\x02\x07\x12\x031\x02\x18\
    \x1a)\x20For\x20ADMITTED:\x20JWT\x20to\x20upgrade\x20connection\n\n\x0c\
    \n\x05\x04\0\x02\x07\x05\x12\x031\x02\x08\n\x0c\n\x05\x04\0\x02\x07\x01\
    \x12\x031\t\x13\n\x0c\n\x05\x04\0\x02\x07\x03\x12\x031\x16\x17\n\x0b\n\
    \x04\x04\0\x02\x08\x12\x032\x02\x18\n\x0c\n\x05\x04\0\x02\x08\x05\x12\
    \x032\x02\x08\n\x0c\n\x05\x04\0\x02\x08\x01\x12\x032\t\x13\n\x0c\n\x05\
    \x04\0\x02\x08\x03\x12\x032\x16\x17\nS\n\x04\x04\0\x02\t\x12\x034\x02\
    \x1a\x1aF\x20Display\x20name\x20of\x20the\x20participant\x20(for\x20PART\
    ICIPANT_JOINED/LEFT\x20events)\n\n\x0c\n\x05\x04\0\x02\t\x05\x12\x034\
    \x02\x07\n\x0c\n\x05\x04\0\x02\t\x01\x12\x034\x08\x14\n\x0c\n\x05\x04\0\
    \x02\t\x03\x12\x034\x17\x19\n\xfe\x01\n\x04\x04\0\x02\n\x12\x039\x02\x15\
    \x1a\xf0\x01\x20Whether\x20the\x20participant\x20joined\x20as\x20an\x20u\
    nauthenticated\x20guest\n\x20(for\x20PARTICIPANT_JOINED/LEFT\x20events).\
    \x20Sourced\x20from\x20the\n\x20authenticated\x20JWT\x20is_guest\x20clai\
    m\x20on\x20the\x20server.\x20Default\x20false\n\x20keeps\x20the\x20wire\
    \x20format\x20backward-compatible\x20with\x20older\x20peers.\n\n\x0c\n\
    \x05\x04\0\x02\n\x05\x12\x039\x02\x06\n\x0c\n\x05\x04\0\x02\n\x01\x12\
    \x039\x07\x0f\n\x0c\n\x05\x04\0\x02\n\x03\x12\x039\x12\x14\n\xb8\x08\n\
    \x04\x04\0\x02\x0b\x12\x03L\x02$\x1a\xaa\x08\x20For\x20PARTICIPANT_LIST_\
    REQUEST:\x20the\x20requesting\x20joiner's\x20CLAIMED\x20per-tab\n\x20ins\
    tance_id.\x20Relay-internal\x20\xe2\x80\x94\x20PARTICIPANT_LIST_REQUEST\
    \x20is\x20consumed\x20by\n\x20the\x20receiving\x20relay\x20and\x20never\
    \x20forwarded\x20to\x20clients.\n\n\x20NOT\x20server-authoritative.\x20T\
    he\x20value\x20originates\x20as\x20the\x20client's\x20own\n\x20?instance\
    _id=\x20connect\x20parameter;\x20the\x20joiner's\x20relay\x20copies\x20i\
    t\x20onto\x20the\n\x20wire\x20after\x20a\x20length/emptiness\x20check\
    \x20only,\x20and\x20never\x20checks\x20it\x20against\n\x20the\x20authent\
    icated\x20JWT\x20sub.\x20Treat\x20it\x20as\x20a\x20hint\x20a\x20client\
    \x20could\x20forge.\n\n\x20It\x20lets\x20a\x20responding\x20relay\x20cou\
    nt\x20one\x20client's\x20dual\x20election\x20candidate\n\x20sessions\x20\
    (WS\x20+\x20WT,\x20distinct\x20session_id,\x20same\x20instance_id)\x20as\
    \x20ONE\n\x20distinct\x20requester,\x20which\x20selects\x20a\x20unicast\
    \x20re-announce\x20instead\x20of\x20a\n\x20broadcast.\x20That\x20is\x20t\
    he\x20only\x20decision\x20keyed\x20on\x20it,\x20and\x20a\x20false\x20cla\
    im\n\x20resolves\x20toward\x20broadcast\x20\xe2\x80\x94\x20reaching\x20m\
    ore\x20sessions,\x20never\x20fewer\x20\xe2\x80\x94\x20so\x20a\n\x20forge\
    d\x20value\x20cannot\x20withhold\x20a\x20presence\x20answer\x20from\x20a\
    nyone.\x20Empty\x20when\n\x20the\x20joiner\x20supplied\x20no\x20instance\
    _id\x20or\x20the\x20request\x20came\x20from\x20an\x20older\n\x20relay;\
    \x20receivers\x20then\x20fall\x20back\x20to\x20keying\x20on\x20session_i\
    d,\x20which\x20is\x20the\n\x20pre-#1600\x20behaviour.\n\n\x0c\n\x05\x04\
    \0\x02\x0b\x05\x12\x03L\x02\x08\n\x0c\n\x05\x04\0\x02\x0b\x01\x12\x03L\t\
    \x1e\n\x0c\n\x05\x04\0\x02\x0b\x03\x12\x03L!#b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(MeetingPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(meeting_packet::MeetingEventType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
