// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/meeting_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

///  Meeting lifecycle messages sent between server and clients
// @@protoc_insertion_point(message:MeetingPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MeetingPacket {
    // message fields
    // @@protoc_insertion_point(field:MeetingPacket.event_type)
    pub event_type: ::protobuf::EnumOrUnknown<meeting_packet::MeetingEventType>,
    // @@protoc_insertion_point(field:MeetingPacket.room_id)
    pub room_id: ::std::string::String,
    // @@protoc_insertion_point(field:MeetingPacket.start_time_ms)
    pub start_time_ms: u64,
    // @@protoc_insertion_point(field:MeetingPacket.message)
    pub message: ::std::string::String,
    // @@protoc_insertion_point(field:MeetingPacket.creator_id)
    pub creator_id: ::std::string::String,
    // @@protoc_insertion_point(field:MeetingPacket.participant_count)
    pub participant_count: i64,
    ///  For ADMITTED/REJECTED: affected user's ID
    // @@protoc_insertion_point(field:MeetingPacket.target_user_id)
    pub target_user_id: ::std::string::String,
    ///  For ADMITTED: JWT to upgrade connection
    // @@protoc_insertion_point(field:MeetingPacket.room_token)
    pub room_token: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:MeetingPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MeetingPacket {
    fn default() -> &'a MeetingPacket {
        <MeetingPacket as ::protobuf::Message>::default_instance()
    }
}

impl MeetingPacket {
    pub fn new() -> MeetingPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "event_type",
            |m: &MeetingPacket| { &m.event_type },
            |m: &mut MeetingPacket| { &mut m.event_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "room_id",
            |m: &MeetingPacket| { &m.room_id },
            |m: &mut MeetingPacket| { &mut m.room_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "start_time_ms",
            |m: &MeetingPacket| { &m.start_time_ms },
            |m: &mut MeetingPacket| { &mut m.start_time_ms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "message",
            |m: &MeetingPacket| { &m.message },
            |m: &mut MeetingPacket| { &mut m.message },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "creator_id",
            |m: &MeetingPacket| { &m.creator_id },
            |m: &mut MeetingPacket| { &mut m.creator_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "participant_count",
            |m: &MeetingPacket| { &m.participant_count },
            |m: &mut MeetingPacket| { &mut m.participant_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "target_user_id",
            |m: &MeetingPacket| { &m.target_user_id },
            |m: &mut MeetingPacket| { &mut m.target_user_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "room_token",
            |m: &MeetingPacket| { &m.room_token },
            |m: &mut MeetingPacket| { &mut m.room_token },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MeetingPacket>(
            "MeetingPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MeetingPacket {
    const NAME: &'static str = "MeetingPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.event_type = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.room_id = is.read_string()?;
                },
                24 => {
                    self.start_time_ms = is.read_uint64()?;
                },
                34 => {
                    self.message = is.read_string()?;
                },
                42 => {
                    self.creator_id = is.read_string()?;
                },
                48 => {
                    self.participant_count = is.read_int64()?;
                },
                58 => {
                    self.target_user_id = is.read_string()?;
                },
                66 => {
                    self.room_token = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.event_type != ::protobuf::EnumOrUnknown::new(meeting_packet::MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN) {
            my_size += ::protobuf::rt::int32_size(1, self.event_type.value());
        }
        if !self.room_id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.room_id);
        }
        if self.start_time_ms != 0 {
            my_size += ::protobuf::rt::uint64_size(3, self.start_time_ms);
        }
        if !self.message.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.message);
        }
        if !self.creator_id.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.creator_id);
        }
        if self.participant_count != 0 {
            my_size += ::protobuf::rt::int64_size(6, self.participant_count);
        }
        if !self.target_user_id.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.target_user_id);
        }
        if !self.room_token.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.room_token);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.event_type != ::protobuf::EnumOrUnknown::new(meeting_packet::MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.event_type))?;
        }
        if !self.room_id.is_empty() {
            os.write_string(2, &self.room_id)?;
        }
        if self.start_time_ms != 0 {
            os.write_uint64(3, self.start_time_ms)?;
        }
        if !self.message.is_empty() {
            os.write_string(4, &self.message)?;
        }
        if !self.creator_id.is_empty() {
            os.write_string(5, &self.creator_id)?;
        }
        if self.participant_count != 0 {
            os.write_int64(6, self.participant_count)?;
        }
        if !self.target_user_id.is_empty() {
            os.write_string(7, &self.target_user_id)?;
        }
        if !self.room_token.is_empty() {
            os.write_string(8, &self.room_token)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MeetingPacket {
        MeetingPacket::new()
    }

    fn clear(&mut self) {
        self.event_type = ::protobuf::EnumOrUnknown::new(meeting_packet::MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN);
        self.room_id.clear();
        self.start_time_ms = 0;
        self.message.clear();
        self.creator_id.clear();
        self.participant_count = 0;
        self.target_user_id.clear();
        self.room_token.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MeetingPacket {
        static instance: MeetingPacket = MeetingPacket {
            event_type: ::protobuf::EnumOrUnknown::from_i32(0),
            room_id: ::std::string::String::new(),
            start_time_ms: 0,
            message: ::std::string::String::new(),
            creator_id: ::std::string::String::new(),
            participant_count: 0,
            target_user_id: ::std::string::String::new(),
            room_token: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MeetingPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MeetingPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MeetingPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MeetingPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `MeetingPacket`
pub mod meeting_packet {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:MeetingPacket.MeetingEventType)
    pub enum MeetingEventType {
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.MEETING_EVENT_TYPE_UNKNOWN)
        MEETING_EVENT_TYPE_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.MEETING_STARTED)
        MEETING_STARTED = 1,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.MEETING_ENDED)
        MEETING_ENDED = 2,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_JOINED)
        PARTICIPANT_JOINED = 3,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_LEFT)
        PARTICIPANT_LEFT = 4,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.MEETING_ACTIVATED)
        MEETING_ACTIVATED = 5,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_ADMITTED)
        PARTICIPANT_ADMITTED = 6,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.PARTICIPANT_REJECTED)
        PARTICIPANT_REJECTED = 7,
        // @@protoc_insertion_point(enum_value:MeetingPacket.MeetingEventType.WAITING_ROOM_UPDATED)
        WAITING_ROOM_UPDATED = 8,
    }

    impl ::protobuf::Enum for MeetingEventType {
        const NAME: &'static str = "MeetingEventType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<MeetingEventType> {
            match value {
                0 => ::std::option::Option::Some(MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN),
                1 => ::std::option::Option::Some(MeetingEventType::MEETING_STARTED),
                2 => ::std::option::Option::Some(MeetingEventType::MEETING_ENDED),
                3 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_JOINED),
                4 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_LEFT),
                5 => ::std::option::Option::Some(MeetingEventType::MEETING_ACTIVATED),
                6 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_ADMITTED),
                7 => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_REJECTED),
                8 => ::std::option::Option::Some(MeetingEventType::WAITING_ROOM_UPDATED),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<MeetingEventType> {
            match str {
                "MEETING_EVENT_TYPE_UNKNOWN" => ::std::option::Option::Some(MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN),
                "MEETING_STARTED" => ::std::option::Option::Some(MeetingEventType::MEETING_STARTED),
                "MEETING_ENDED" => ::std::option::Option::Some(MeetingEventType::MEETING_ENDED),
                "PARTICIPANT_JOINED" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_JOINED),
                "PARTICIPANT_LEFT" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_LEFT),
                "MEETING_ACTIVATED" => ::std::option::Option::Some(MeetingEventType::MEETING_ACTIVATED),
                "PARTICIPANT_ADMITTED" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_ADMITTED),
                "PARTICIPANT_REJECTED" => ::std::option::Option::Some(MeetingEventType::PARTICIPANT_REJECTED),
                "WAITING_ROOM_UPDATED" => ::std::option::Option::Some(MeetingEventType::WAITING_ROOM_UPDATED),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [MeetingEventType] = &[
            MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN,
            MeetingEventType::MEETING_STARTED,
            MeetingEventType::MEETING_ENDED,
            MeetingEventType::PARTICIPANT_JOINED,
            MeetingEventType::PARTICIPANT_LEFT,
            MeetingEventType::MEETING_ACTIVATED,
            MeetingEventType::PARTICIPANT_ADMITTED,
            MeetingEventType::PARTICIPANT_REJECTED,
            MeetingEventType::WAITING_ROOM_UPDATED,
        ];
    }

    impl ::protobuf::EnumFull for MeetingEventType {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("MeetingPacket.MeetingEventType").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for MeetingEventType {
        fn default() -> Self {
            MeetingEventType::MEETING_EVENT_TYPE_UNKNOWN
        }
    }

    impl MeetingEventType {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<MeetingEventType>("MeetingPacket.MeetingEventType")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1atypes/meeting_packet.proto\"\xa7\x04\n\rMeetingPacket\x12>\n\neven\
    t_type\x18\x01\x20\x01(\x0e2\x1f.MeetingPacket.MeetingEventTypeR\teventT\
    ype\x12\x17\n\x07room_id\x18\x02\x20\x01(\tR\x06roomId\x12\"\n\rstart_ti\
    me_ms\x18\x03\x20\x01(\x04R\x0bstartTimeMs\x12\x18\n\x07message\x18\x04\
    \x20\x01(\tR\x07message\x12\x1d\n\ncreator_id\x18\x05\x20\x01(\tR\tcreat\
    orId\x12+\n\x11participant_count\x18\x06\x20\x01(\x03R\x10participantCou\
    nt\x12$\n\x0etarget_user_id\x18\x07\x20\x01(\tR\x0ctargetUserId\x12\x1d\
    \n\nroom_token\x18\x08\x20\x01(\tR\troomToken\"\xed\x01\n\x10MeetingEven\
    tType\x12\x1e\n\x1aMEETING_EVENT_TYPE_UNKNOWN\x10\0\x12\x13\n\x0fMEETING\
    _STARTED\x10\x01\x12\x11\n\rMEETING_ENDED\x10\x02\x12\x16\n\x12PARTICIPA\
    NT_JOINED\x10\x03\x12\x14\n\x10PARTICIPANT_LEFT\x10\x04\x12\x15\n\x11MEE\
    TING_ACTIVATED\x10\x05\x12\x18\n\x14PARTICIPANT_ADMITTED\x10\x06\x12\x18\
    \n\x14PARTICIPANT_REJECTED\x10\x07\x12\x18\n\x14WAITING_ROOM_UPDATED\x10\
    \x08J\xf6\n\n\x06\x12\x04\0\0\"\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\nH\n\
    \x02\x04\0\x12\x04\x03\0\"\x01\x1a<\x20Meeting\x20lifecycle\x20messages\
    \x20sent\x20between\x20server\x20and\x20clients\n\n\n\n\x03\x04\0\x01\
    \x12\x03\x03\x08\x15\n\x0c\n\x04\x04\0\x04\0\x12\x04\x04\x02\x16\x03\n\
    \x0c\n\x05\x04\0\x04\0\x01\x12\x03\x04\x07\x17\n\r\n\x06\x04\0\x04\0\x02\
    \0\x12\x03\x05\x04#\n\x0e\n\x07\x04\0\x04\0\x02\0\x01\x12\x03\x05\x04\
    \x1e\n\x0e\n\x07\x04\0\x04\0\x02\0\x02\x12\x03\x05!\"\nF\n\x06\x04\0\x04\
    \0\x02\x01\x12\x03\x07\x04\x18\x1a7\x20Meeting\x20started\x20-\x20sent\
    \x20to\x20participants\x20when\x20they\x20join\n\n\x0e\n\x07\x04\0\x04\0\
    \x02\x01\x01\x12\x03\x07\x04\x13\n\x0e\n\x07\x04\0\x04\0\x02\x01\x02\x12\
    \x03\x07\x16\x17\nQ\n\x06\x04\0\x04\0\x02\x02\x12\x03\t\x04\x16\x1aB\x20\
    Meeting\x20ended\x20-\x20sent\x20when\x20host\x20leaves\x20or\x20last\
    \x20participant\x20leaves\n\n\x0e\n\x07\x04\0\x04\0\x02\x02\x01\x12\x03\
    \t\x04\x11\n\x0e\n\x07\x04\0\x04\0\x02\x02\x02\x12\x03\t\x14\x15\n/\n\
    \x06\x04\0\x04\0\x02\x03\x12\x03\x0b\x04\x1b\x1a\x20\x20Participant\x20j\
    oined\x20the\x20meeting\n\n\x0e\n\x07\x04\0\x04\0\x02\x03\x01\x12\x03\
    \x0b\x04\x16\n\x0e\n\x07\x04\0\x04\0\x02\x03\x02\x12\x03\x0b\x19\x1a\n-\
    \n\x06\x04\0\x04\0\x02\x04\x12\x03\r\x04\x19\x1a\x1e\x20Participant\x20l\
    eft\x20the\x20meeting\n\n\x0e\n\x07\x04\0\x04\0\x02\x04\x01\x12\x03\r\
    \x04\x14\n\x0e\n\x07\x04\0\x04\0\x02\x04\x02\x12\x03\r\x17\x18\n0\n\x06\
    \x04\0\x04\0\x02\x05\x12\x03\x0f\x04\x1a\x1a!\x20Host\x20joined,\x20meet\
    ing\x20now\x20active\n\n\x0e\n\x07\x04\0\x04\0\x02\x05\x01\x12\x03\x0f\
    \x04\x15\n\x0e\n\x07\x04\0\x04\0\x02\x05\x02\x12\x03\x0f\x18\x19\n+\n\
    \x06\x04\0\x04\0\x02\x06\x12\x03\x11\x04\x1d\x1a\x1c\x20Admitted\x20from\
    \x20waiting\x20room\n\n\x0e\n\x07\x04\0\x04\0\x02\x06\x01\x12\x03\x11\
    \x04\x18\n\x0e\n\x07\x04\0\x04\0\x02\x06\x02\x12\x03\x11\x1b\x1c\n+\n\
    \x06\x04\0\x04\0\x02\x07\x12\x03\x13\x04\x1d\x1a\x1c\x20Rejected\x20from\
    \x20waiting\x20room\n\n\x0e\n\x07\x04\0\x04\0\x02\x07\x01\x12\x03\x13\
    \x04\x18\n\x0e\n\x07\x04\0\x04\0\x02\x07\x02\x12\x03\x13\x1b\x1c\n*\n\
    \x06\x04\0\x04\0\x02\x08\x12\x03\x15\x04\x1d\x1a\x1b\x20Waiting\x20room\
    \x20list\x20changed\n\n\x0e\n\x07\x04\0\x04\0\x02\x08\x01\x12\x03\x15\
    \x04\x18\n\x0e\n\x07\x04\0\x04\0\x02\x08\x02\x12\x03\x15\x1b\x1c\n\x0b\n\
    \x04\x04\0\x02\0\x12\x03\x18\x02\"\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\
    \x18\x02\x12\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x18\x13\x1d\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\x18\x20!\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x19\
    \x02\x15\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x19\x02\x08\n\x0c\n\x05\
    \x04\0\x02\x01\x01\x12\x03\x19\t\x10\n\x0c\n\x05\x04\0\x02\x01\x03\x12\
    \x03\x19\x13\x14\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x1a\x02\x1b\n\x0c\n\
    \x05\x04\0\x02\x02\x05\x12\x03\x1a\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\
    \x12\x03\x1a\t\x16\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x1a\x19\x1a\n\
    \x0b\n\x04\x04\0\x02\x03\x12\x03\x1b\x02\x15\n\x0c\n\x05\x04\0\x02\x03\
    \x05\x12\x03\x1b\x02\x08\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\x1b\t\x10\
    \n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x1b\x13\x14\n\x0b\n\x04\x04\0\x02\
    \x04\x12\x03\x1c\x02\x18\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\x1c\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\x1c\t\x13\n\x0c\n\x05\x04\0\
    \x02\x04\x03\x12\x03\x1c\x16\x17\n\x0b\n\x04\x04\0\x02\x05\x12\x03\x1d\
    \x02\x1e\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\x1d\x02\x07\n\x0c\n\x05\
    \x04\0\x02\x05\x01\x12\x03\x1d\x08\x19\n\x0c\n\x05\x04\0\x02\x05\x03\x12\
    \x03\x1d\x1c\x1d\n8\n\x04\x04\0\x02\x06\x12\x03\x1f\x02\x1c\x1a+\x20For\
    \x20ADMITTED/REJECTED:\x20affected\x20user's\x20ID\n\n\x0c\n\x05\x04\0\
    \x02\x06\x05\x12\x03\x1f\x02\x08\n\x0c\n\x05\x04\0\x02\x06\x01\x12\x03\
    \x1f\t\x17\n\x0c\n\x05\x04\0\x02\x06\x03\x12\x03\x1f\x1a\x1b\n6\n\x04\
    \x04\0\x02\x07\x12\x03!\x02\x18\x1a)\x20For\x20ADMITTED:\x20JWT\x20to\
    \x20upgrade\x20connection\n\n\x0c\n\x05\x04\0\x02\x07\x05\x12\x03!\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x07\x01\x12\x03!\t\x13\n\x0c\n\x05\x04\0\x02\
    \x07\x03\x12\x03!\x16\x17b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(MeetingPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(meeting_packet::MeetingEventType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
