// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/meeting_timer_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:MeetingTimerPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MeetingTimerPacket {
    // message fields
    ///  Absolute timer state. true = a timer is running and ends at `ends_at_ms`;
    ///  false = NO timer (never started, cancelled, or cleared). NOT a toggle.
    ///
    ///  proto3 omits default values on the wire, so a CANCEL serializes to zero
    ///  bytes for this field — which also means an EMPTY or truncated payload
    ///  parses as `running = false`. That degradation is deliberately the SAFE one:
    ///  the worst a corrupt payload can do is clear the timer, never start one and
    ///  never trigger the expiry sound.
    ///
    ///  WHY THIS FIELD IS NOT REDUNDANT with `ends_at_ms == 0`: a CANCELLED timer
    ///  and an EXPIRED timer must be distinguishable, because they differ in the
    ///  one behaviour users hear. An expired timer (running = true, `ends_at_ms` in
    ///  the past) plays the expiry sound; a cancelled one is silent. With only an
    ///  end instant to go on, a cancel would be indistinguishable from a timer that
    ///  ended at the epoch and every cancel would beep.
    // @@protoc_insertion_point(field:MeetingTimerPacket.running)
    pub running: bool,
    // @@protoc_insertion_point(field:MeetingTimerPacket.ends_at_ms)
    pub ends_at_ms: u64,
    ///  Total span this timer currently represents, in milliseconds — the duration
    ///  the host configured, INCLUDING any extension (an extend from 5 to 8 minutes
    ///  sets 8 minutes here, not 3). Meaningless (send 0) when `running == false`.
    ///
    ///  DISPLAY ONLY. `ends_at_ms` alone is the authoritative countdown; this exists
    ///  so a client can render a proportion (a progress ring, "3:12 of 5:00")
    ///  without a second clock. It is required rather than optional precisely
    ///  BECAUSE of late joiners: a client that joins mid-run has no way to know the
    ///  timer started at five minutes, so a client-side "total" reconstructed from
    ///  first observation would be wrong for exactly the clients this design exists
    ///  to serve.
    ///
    ///  `started_at_ms` is `ends_at_ms - duration_ms`. Compute it with a SATURATING
    ///  subtraction, and likewise for `remaining = ends_at_ms - now`: the relay
    ///  rejects `ends_at_ms < duration_ms` at ingress so the first cannot underflow
    ///  from a conforming relay, but a peer may be running an older one, and the
    ///  SECOND underflows routinely and by design — every timer that has expired has
    ///  `now > ends_at_ms`. An unguarded `u64` subtraction there panics in a debug
    ///  wasm build, which aborts the module and drops the whole call for that tab.
    ///
    ///  Bounded at ingress by MEETING_TIMER_MAX_DURATION_MS (24h); an over-cap value
    ///  DROPS the packet. That bound is arithmetic hygiene, not authorization — the
    ///  host is entitled to any duration within it — and it exists so an unbounded
    ///  u64 cannot overflow client-side arithmetic. The client MUST clamp
    ///  independently before rendering, exactly as it does for REACTION's
    ///  `custom_emoji`: a peer may be running an older or newer relay.
    // @@protoc_insertion_point(field:MeetingTimerPacket.duration_ms)
    pub duration_ms: u64,
    ///  Unix epoch milliseconds at which the host AUTHORED this state, set once at
    ///  the transition that produced it and preserved VERBATIM across every
    ///  heartbeat and repeat of that same state. Re-stamping it on a re-send would
    ///  destroy the ordering guarantee it exists to provide.
    ///
    ///  Its sole consumer is the last-writer-wins comparator in wire contract rule
    ///  (5), which suppresses a reordered packet on the WebTransport datagram path
    ///  — the case where a stale START could otherwise land after a CANCEL and
    ///  resurrect a timer the host already stopped. Read rule (5) before writing
    ///  that comparator: it has a bounded rejection window, and the bound is what
    ///  stops a host clock step from wedging the feature.
    ///
    ///  Same trust class as RaiseHandPacket.raised_at_ms: sender wall clock,
    ///  ADVISORY, never authorization. It cannot be relay-stamped (a heartbeat would
    ///  then be re-stamped later and defeat the comparator), and it cannot be a
    ///  per-client monotonic clock (those have per-tab origins and are not
    ///  comparable across the reconnects this must survive). Forgery is not a
    ///  concern here in the way it is for a raised hand: only the host can send this
    ///  packet at all, and the host can already author any state it wants.
    // @@protoc_insertion_point(field:MeetingTimerPacket.updated_at_ms)
    pub updated_at_ms: u64,
    // special fields
    // @@protoc_insertion_point(special_field:MeetingTimerPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MeetingTimerPacket {
    fn default() -> &'a MeetingTimerPacket {
        <MeetingTimerPacket as ::protobuf::Message>::default_instance()
    }
}

impl MeetingTimerPacket {
    pub fn new() -> MeetingTimerPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "running",
            |m: &MeetingTimerPacket| { &m.running },
            |m: &mut MeetingTimerPacket| { &mut m.running },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ends_at_ms",
            |m: &MeetingTimerPacket| { &m.ends_at_ms },
            |m: &mut MeetingTimerPacket| { &mut m.ends_at_ms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "duration_ms",
            |m: &MeetingTimerPacket| { &m.duration_ms },
            |m: &mut MeetingTimerPacket| { &mut m.duration_ms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "updated_at_ms",
            |m: &MeetingTimerPacket| { &m.updated_at_ms },
            |m: &mut MeetingTimerPacket| { &mut m.updated_at_ms },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MeetingTimerPacket>(
            "MeetingTimerPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MeetingTimerPacket {
    const NAME: &'static str = "MeetingTimerPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.running = is.read_bool()?;
                },
                16 => {
                    self.ends_at_ms = is.read_uint64()?;
                },
                24 => {
                    self.duration_ms = is.read_uint64()?;
                },
                32 => {
                    self.updated_at_ms = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.running != false {
            my_size += 1 + 1;
        }
        if self.ends_at_ms != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.ends_at_ms);
        }
        if self.duration_ms != 0 {
            my_size += ::protobuf::rt::uint64_size(3, self.duration_ms);
        }
        if self.updated_at_ms != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.updated_at_ms);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.running != false {
            os.write_bool(1, self.running)?;
        }
        if self.ends_at_ms != 0 {
            os.write_uint64(2, self.ends_at_ms)?;
        }
        if self.duration_ms != 0 {
            os.write_uint64(3, self.duration_ms)?;
        }
        if self.updated_at_ms != 0 {
            os.write_uint64(4, self.updated_at_ms)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MeetingTimerPacket {
        MeetingTimerPacket::new()
    }

    fn clear(&mut self) {
        self.running = false;
        self.ends_at_ms = 0;
        self.duration_ms = 0;
        self.updated_at_ms = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MeetingTimerPacket {
        static instance: MeetingTimerPacket = MeetingTimerPacket {
            running: false,
            ends_at_ms: 0,
            duration_ms: 0,
            updated_at_ms: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MeetingTimerPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MeetingTimerPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MeetingTimerPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MeetingTimerPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x20types/meeting_timer_packet.proto\"\x91\x01\n\x12MeetingTimerPacket\
    \x12\x18\n\x07running\x18\x01\x20\x01(\x08R\x07running\x12\x1c\n\nends_a\
    t_ms\x18\x02\x20\x01(\x04R\x08endsAtMs\x12\x1f\n\x0bduration_ms\x18\x03\
    \x20\x01(\x04R\ndurationMs\x12\"\n\rupdated_at_ms\x18\x04\x20\x01(\x04R\
    \x0bupdatedAtMsJ\xcer\n\x07\x12\x05\0\0\xef\x01\x01\n\x08\n\x01\x0c\x12\
    \x03\0\0\x12\n\xd5A\n\x02\x04\0\x12\x06\x89\x01\0\xef\x01\x01\x1a\xc6A\
    \x20Host\x20->\x20relay\x20->\x20all-peers\x20MEETING\x20TIMER\x20STATE\
    \x20broadcast\x20(issue\x20#2136).\n\x20Carried\x20inside\x20a\x20Packet\
    Wrapper\x20whose\x20packet_type\x20is\x20MEETING_TIMER\x20(19).\n\n\x20N\
    OT\x20`MEETING`\x20(7).\x20Read\x20this\x20before\x20adding\x20any\x20ar\
    m\x20that\x20handles\x20either.\n\x20The\x20two\x20are\x20adjacent\x20in\
    \x20name\x20and\x20OPPOSITE\x20in\x20trust\x20model:\n\x20\x20\x20*\x20M\
    EETING\x20(7)\x20is\x20SERVER-AUTHORED.\x20meeting-api\x20publishes\x20i\
    t\x20on\n\x20\x20\x20\x20\x20room.{id}.system\x20after\x20a\x20DB-backed\
    \x20`require_host`\x20check,\x20and\n\x20\x20\x20\x20\x20`classify_packe\
    t`\x20DROPS\x20every\x20client-originated\x20MEETING\x20packet\n\x20\x20\
    \x20\x20\x20unconditionally.\n\x20\x20\x20*\x20MEETING_TIMER\x20(19)\x20\
    is\x20CLIENT-AUTHORED\x20by\x20the\x20host\x20and\x20RE-BROADCAST\x20by\
    \n\x20\x20\x20\x20\x20the\x20relay,\x20like\x20REACTION\x20(17).\x20Its\
    \x20authorization\x20is\x20enforced\x20by\x20the\n\x20\x20\x20\x20\x20re\
    lay\x20itself\x20(see\x20AUTHORIZATION\x20below),\x20not\x20by\x20meetin\
    g-api.\n\x20A\x20new\x20drop/forward\x20arm\x20written\x20on\x20the\x20a\
    ssumption\x20that\x20\"meeting-ish\x20packets\n\x20are\x20server-authore\
    d\"\x20would\x20be\x20wrong\x20for\x20exactly\x20one\x20of\x20these.\n\n\
    \x20WHAT\x20IT\x20IS.\x20The\x20host\x20sets\x20a\x20countdown\x20that\
    \x20every\x20participant\x20sees\x20\xe2\x80\x94\x20the\n\x20motivating\
    \x20use\x20case\x20is\x20bounding\x20a\x20presenter's\x20slot\x20\xe2\
    \x80\x94\x20and\x20when\x20it\x20reaches\x20zero\n\x20every\x20participa\
    nt\x20plays\x20an\x20expiry\x20sound.\n\n\x20STATE,\x20NOT\x20AN\x20EVEN\
    T.\x20`running`\x20is\x20an\x20absolute\x20level\x20(\"a\x20timer\x20is\
    \x20running\n\x20until\x20T\"\x20/\x20\"no\x20timer\"),\x20never\x20a\
    \x20toggle,\x20so\x20re-sending\x20the\x20SAME\x20value\x20is\x20a\n\x20\
    harmless\x20no-op\x20for\x20every\x20consumer.\x20That\x20idempotence\
    \x20is\x20what\x20makes\x20the\n\x20RE-ANNOUNCE\x20protocol\x20below\x20\
    safe,\x20and\x20it\x20is\x20why\x20the\x20relay\x20can\x20stay\x20a\x20d\
    umb\n\x20forwarder\x20with\x20NO\x20server-side\x20timer\x20registry.\
    \x20A\x20toggle-shaped\x20message\x20would\n\x20let\x20a\x20single\x20lo\
    st\x20or\x20duplicated\x20packet\x20invert\x20the\x20room's\x20view\x20p\
    ermanently.\n\x20CANCEL\x20is\x20therefore\x20a\x20state\x20transition\
    \x20(`running\x20=\x20false`),\x20not\x20a\x20separate\n\x20message\x20t\
    ype.\n\n\x20ABSOLUTE\x20END\x20TIME,\x20NOT\x20SECONDS-REMAINING\x20\xe2\
    \x80\x94\x20the\x20decision\x20everything\x20else\n\x20follows\x20from.\
    \x20`ends_at_ms`\x20is\x20a\x20wall-clock\x20INSTANT,\x20so\x20a\x20clie\
    nt\x20that\x20joins\x20or\n\x20reconnects\x20mid-run\x20computes\x20its\
    \x20own\x20remaining\x20time\x20from\x20ONE\x20number\x20and\x20is\n\x20\
    immediately\x20correct.\x20A\x20seconds-remaining\x20encoding\x20would\
    \x20need\x20continuous\n\x20re-sync\x20to\x20stay\x20accurate\x20and\x20\
    would\x20drift\x20between\x20the\x20re-syncs;\x20an\x20absolute\n\x20ins\
    tant\x20is\x20late-joiner-correct\x20and\x20reconnect-safe\x20for\x20fre\
    e.\x20The\x20cost\x20is\n\x20host/viewer\x20clock\x20skew,\x20analysed\
    \x20on\x20`ends_at_ms`\x20below.\n\n\x20AUTHORIZATION:\x20HOST-ONLY,\x20\
    ENFORCED\x20BY\x20THE\x20RELAY.\n\x20Only\x20the\x20meeting\x20HOST\x20m\
    ay\x20start,\x20extend\x20or\x20cancel\x20a\x20timer,\x20and\x20that\x20\
    is\n\x20enforced\x20server-side\x20\xe2\x80\x94\x20a\x20modified\x20clie\
    nt\x20that\x20is\x20not\x20the\x20host\x20cannot\x20inject\n\x20one.\x20\
    The\x20check\x20is\x20NOT\x20the\x20sending\x20session's\x20JWT\x20`is_h\
    ost`\x20claim:\x20that\x20claim\n\x20is\x20frozen\x20at\x20token-mint\
    \x20time\x20and\x20goes\x20stale\x20in\x20BOTH\x20directions\x20after\
    \x20a\n\x20transfer-host\x20(the\x20demoted\x20ex-host\x20keeps\x20a\x20\
    `true`\x20claim;\x20the\x20newly\x20promoted\n\x20host\x20holds\x20a\x20\
    `false`\x20one\x20until\x20it\x20reconnects).\x20The\x20relay\x20instead\
    \x20gates\x20on\x20its\n\x20live\x20per-room\x20presence\x20mirror,\x20w\
    hich\x20`internal.meeting_host_changed`\x20keeps\x20in\n\x20step\x20with\
    \x20the\x20authoritative\x20`meeting_participants.is_host`\x20column.\
    \x20See\n\x20`ClientMessage.requires_host`\x20and\x20`session_is_room_ho\
    st`\x20in\x20actix-api.\n\n\x20\"Host\",\x20not\x20\"owner\",\x20is\x20d\
    eliberate.\x20`meetings.creator_id`\x20(the\x20immutable\n\x20creator,\
    \x20surfaced\x20to\x20the\x20UI\x20as\x20`is_owner`)\x20never\x20reaches\
    \x20the\x20relay\x20at\x20all\x20\xe2\x80\x94\n\x20it\x20is\x20not\x20a\
    \x20JWT\x20claim\x20and\x20travels\x20on\x20no\x20NATS\x20subject.\x20Th\
    e\x20transferable\n\x20`is_host`\x20role\x20is\x20what\x20every\x20other\
    \x20host\x20control\x20in\x20this\x20product\x20authorizes\x20on\n\x20(`\
    require_host`\x20in\x20meeting-api\x20gates\x20mute-all,\x20kick,\x20and\
    \x20transfer-host),\x20it\x20is\n\x20exclusive\x20(at\x20most\x20one\x20\
    row\x20per\x20meeting),\x20and\x20it\x20is\x20what\x20\"the\x20host\x20o\
    f\x20the\n\x20meeting\"\x20means\x20to\x20a\x20user\x20after\x20a\x20tra\
    nsfer.\n\n\x20NOT\x20E2EE-sealed:\x20CLEARTEXT\x20even\x20when\x20E2EE_E\
    NABLED=true,\x20mirroring\n\x20ReactionPacket,\x20because\x20the\x20rela\
    y\x20must\x20read\x20the\x20inner\x20packet\x20to\x20enforce\n\x20ingres\
    s\x20validation\x20(size\x20cap\x20+\x20`duration_ms`\x20bound)\x20and\
    \x20a\x20meeting\x20timer\x20is\n\x20broadcast-public\x20by\x20definitio\
    n.\x20Put\x20NO\x20private\x20data\x20in\x20this\x20message.\x20Note\n\
    \x20there\x20is\x20deliberately\x20NO\x20string\x20field\x20here\x20\xe2\
    \x80\x94\x20no\x20label,\x20no\x20display\x20name\x20\xe2\x80\x94\x20so\
    \n\x20unlike\x20REACTION\x20and\x20RAISE_HAND\x20this\x20packet\x20carri\
    es\x20no\x20attacker-controlled\n\x20text\x20and\x20needs\x20no\x20trunc\
    ation\x20or\x20escaping\x20on\x20either\x20side.\n\n\x20----------------\
    -----------------------------------------------------------\n\x20WIRE\
    \x20CONTRACT\x20FOR\x20THE\x20CLIENT\x20HALF.\x20These\x20rules\x20are\
    \x20not\x20optional;\x20the\x20relay\n\x20cannot\x20enforce\x20them\x20a\
    nd\x20the\x20feature\x20is\x20incorrect\x20without\x20them.\n\x20-------\
    --------------------------------------------------------------------\n\n\
    \x20(1)\x20HEARTBEAT\x20WHILE\x20RUNNING.\x20While\x20`running\x20==\x20\
    true`\x20the\x20host\x20RE-SENDS\x20the\n\x20\x20\x20\x20\x20current\x20\
    state\x20every\x20~5s,\x20with\x20`ends_at_ms`\x20and\x20`updated_at_ms`\
    \x20preserved\n\x20\x20\x20\x20\x20VERBATIM.\x20This\x20single\x20rule\
    \x20does\x20three\x20jobs:\n\x20\x20\x20\x20\x20\x20\x20*\x20a\x20late\
    \x20joiner\x20sees\x20the\x20timer\x20within\x20one\x20interval,\x20with\
    \x20no\x20join-event\n\x20\x20\x20\x20\x20\x20\x20\x20\x20plumbing\x20at\
    \x20all;\n\x20\x20\x20\x20\x20\x20\x20*\x20a\x20client\x20that\x20reconn\
    ected\x20mid-run\x20recovers\x20the\x20same\x20way;\n\x20\x20\x20\x20\
    \x20\x20\x20*\x20a\x20packet\x20LOST\x20on\x20the\x20WebTransport\x20pat\
    h\x20(see\x20LOSS\x20below)\x20is\x20repaired.\n\x20\x20\x20\x20\x20Only\
    \x20ONE\x20session\x20in\x20the\x20room\x20\xe2\x80\x94\x20the\x20host\
    \x20\xe2\x80\x94\x20ever\x20sends\x20this,\x20which\x20is\x20why\x20a\n\
    \x20\x20\x20\x20\x20heartbeat\x20is\x20affordable\x20here\x20and\x20is\
    \x20NOT\x20the\x20design\x20RaiseHandPacket\x20(#2135)\n\x20\x20\x20\x20\
    \x20could\x20use:\x20there,\x20every\x20participant\x20announces\x20its\
    \x20own\x20state,\x20so\x20a\n\x20\x20\x20\x20\x20heartbeat\x20would\x20\
    have\x20been\x20O(participants).\n\n\x20(2)\x20REPEAT\x20EVERY\x20TRANSI\
    TION.\x20A\x20start,\x20an\x20extend,\x20and\x20above\x20all\x20a\x20CAN\
    CEL\x20are\n\x20\x20\x20\x20\x20sent\x203\x20times,\x20~1s\x20apart,\x20\
    with\x20`updated_at_ms`\x20preserved\x20verbatim\x20across\n\x20\x20\x20\
    \x20\x20the\x20repeats.\x20A\x20cancel\x20has\x20no\x20heartbeat\x20to\
    \x20repair\x20it\x20\xe2\x80\x94\x20once\x20`running`\x20is\n\x20\x20\
    \x20\x20\x20false\x20the\x20host\x20stops\x20sending\x20\xe2\x80\x94\x20\
    so\x20a\x20single\x20lost\x20cancel\x20would\x20otherwise\n\x20\x20\x20\
    \x20\x20leave\x20that\x20peer\x20counting\x20down\x20to\x20an\x20audible\
    \x20expiry\x20the\x20host\x20already\n\x20\x20\x20\x20\x20called\x20off.\
    \x20Rule\x20(5)\x20makes\x20every\x20repeat\x20a\x20no-op\x20for\x20anyo\
    ne\x20who\x20got\x20the\n\x20\x20\x20\x20\x20first\x20copy.\n\n\x20(3)\
    \x20LOSS\x20AND\x20REORDERING\x20ARE\x20REAL\x20ON\x20WEBTRANSPORT.\x20T\
    his\x20packet\x20is\x20small\x20and\n\x20\x20\x20\x20\x20non-media,\x20a\
    nd\x20the\x20WT\x20outbound\x20router\x20sends\x20exactly\x20that\x20cla\
    ss\x20over\x20a\n\x20\x20\x20\x20\x20QUIC\x20DATAGRAM\x20\xe2\x80\x94\
    \x20unreliable\x20and\x20unordered.\x20Concretely:\x20`build_outbound`\
    \x20in\n\x20\x20\x20\x20\x20wt_chat_session.rs\x20routes\x20rule\x201,\
    \x20\"non-media,\x20fits\x20MTU\x20->\x20datagram\",\x20and\n\x20\x20\
    \x20\x20\x20`is_media`\x20there\x20is\x20`packet_type\x20==\x20PacketTyp\
    e::MEDIA`,\x20which\n\x20\x20\x20\x20\x20MEETING_TIMER\x20is\x20not;\x20\
    the\x20whole\x20packet\x20is\x20~35\x20bytes,\x20far\x20inside\n\x20\x20\
    \x20\x20\x20DATAGRAM_MAX_SIZE.\x20On\x20WebSocket\x20(the\x20default\x20\
    transport\x20since\x20#2045)\x20the\n\x20\x20\x20\x20\x20path\x20is\x20T\
    CP\x20behind\x20a\x20single-publisher\x20NATS\x20subject,\x20so\x20it\
    \x20does\x20not\n\x20\x20\x20\x20\x20REORDER\x20\xe2\x80\x94\x20but\x20i\
    t\x20is\x20not\x20loss-free\x20either:\x20this\x20class\x20is\n\x20\x20\
    \x20\x20\x20OutboundPriority::Control,\x20which\x20is\x20never\x20preemp\
    tively\x20shed,\x20yet\x20a\x20full\n\x20\x20\x20\x20\x20outbound\x20cha\
    nnel\x20still\x20drops\x20it\x20(`TrySendError::Full`\x20->\x20`channel_\
    full`).\n\x20\x20\x20\x20\x20So\x20rule\x20(1)\x20earns\x20its\x20keep\
    \x20on\x20BOTH\x20transports\x20and\x20only\x20rule\x20(5)\x20is\n\x20\
    \x20\x20\x20\x20WT-specific.\x20Do\x20not\x20simplify\x20any\x20of\x20th\
    em\x20away\x20on\x20the\x20grounds\x20that\x20\"the\n\x20\x20\x20\x20\
    \x20default\x20transport\x20is\x20reliable\".\n\n\x20(2b)\x20DEBOUNCE\
    \x20RAPID\x20TRANSITIONS.\x20Three\x20\"+1\x20min\"\x20clicks\x20in\x20t\
    wo\x20seconds\x20would\x20be\n\x20\x20\x20\x20\x203\x20transitions\x20x\
    \x203\x20repeats\x20+\x20a\x20heartbeat\x20=\x2010\x20packets,\x20over\
    \x20the\x20relay's\n\x20\x20\x20\x20\x20per-sender\x20budget,\x20and\x20\
    the\x20drops\x20would\x20land\x20on\x20the\x20LAST\x20burst\x20\xe2\x80\
    \x94\x20the\x20one\n\x20\x20\x20\x20\x20carrying\x20the\x20state\x20that\
    \x20matters.\x20Coalesce\x20a\x20rapid\x20run\x20of\x20adjustments\x20in\
    to\n\x20\x20\x20\x20\x20ONE\x20repeat\x20burst\x20for\x20the\x20settled\
    \x20state.\x20Every\x20intermediate\x20state\x20is\x20a\n\x20\x20\x20\
    \x20\x20value\x20the\x20host\x20has\x20already\x20changed,\x20so\x20noth\
    ing\x20is\x20lost\x20by\x20not\x20sending\x20it.\n\n\x20(4)\x20COMPUTE\
    \x20THE\x20COUNTDOWN\x20AGAINST\x20A\x20MONOTONIC\x20CLOCK.\x20On\x20rec\
    eipt,\x20sample\n\x20\x20\x20\x20\x20`remaining\x20=\x20ends_at_ms\x20-\
    \x20now_wall_clock`\x20ONCE,\x20then\x20count\x20that\x20remaining\n\x20\
    \x20\x20\x20\x20span\x20down\x20with\x20a\x20monotonic\x20clock\x20(`per\
    formance.now()`),\x20not\x20by\n\x20\x20\x20\x20\x20re-evaluating\x20`Da\
    te.now()`\x20each\x20tick.\x20Clock\x20skew\x20then\x20enters\x20exactly\
    \x20once,\n\x20\x20\x20\x20\x20at\x20receipt,\x20instead\x20of\x20being\
    \x20re-applied\x20every\x20tick,\x20and\x20a\x20wall-clock\x20STEP\n\x20\
    \x20\x20\x20\x20after\x20receipt\x20(an\x20NTP\x20correction,\x20a\x20ma\
    nual\x20change)\x20cannot\x20jump\x20or\x20freeze\x20a\n\x20\x20\x20\x20\
    \x20running\x20countdown.\x20Clamp\x20the\x20rendered\x20remaining\x20to\
    \x20>=\x200\x20and\x20never\x20render\x20a\n\x20\x20\x20\x20\x20negative\
    \x20value.\n\n\x20(5)\x20LAST-WRITER-WINS\x20ON\x20`updated_at_ms`,\x20W\
    ITH\x20A\x20BOUNDED\x20REJECTION\x20WINDOW.\n\x20\x20\x20\x20\x20Apply\
    \x20an\x20incoming\x20packet\x20unless\x20it\x20is\x20older\x20than\x20t\
    he\x20currently\x20applied\n\x20\x20\x20\x20\x20state\x20by\x20no\x20mor\
    e\x20than\x20~5s:\n\n\x20\x20\x20\x20\x20\x20\x20\x20\x20reject\x20iff\
    \x20\x200\x20<\x20applied.updated_at_ms\x20-\x20incoming.updated_at_ms\
    \x20<=\x205000\n\n\x20\x20\x20\x20\x20The\x20upper\x20bound\x20is\x20loa\
    d-bearing\x20and\x20is\x20the\x20whole\x20point.\x20Nothing\x20on\x20any\
    \x20of\n\x20\x20\x20\x20\x20these\x20paths\x20is\x20in\x20flight\x20for\
    \x205\x20seconds,\x20so\x20a\x20packet\x20that\x20is\x20older\x20by\x20M\
    ORE\n\x20\x20\x20\x20\x20than\x20that\x20is\x20not\x20reordering\x20\xe2\
    \x80\x94\x20it\x20is\x20a\x20host\x20wall-clock\x20step\x20backwards,\
    \x20and\n\x20\x20\x20\x20\x20an\x20unbounded\x20`incoming\x20<\x20applie\
    d\x20->\x20reject`\x20comparator\x20would\x20then\x20reject\n\x20\x20\
    \x20\x20\x20every\x20subsequent\x20state\x20the\x20host\x20authored,\x20\
    INCLUDING\x20THE\x20CANCEL,\x20wedging\x20a\n\x20\x20\x20\x20\x20timer\
    \x20nobody\x20can\x20stop\x20until\x20it\x20expires\x20and\x20beeps\x20a\
    t\x20the\x20whole\x20room.\x20That\n\x20\x20\x20\x20\x20is\x20the\x20#21\
    22\x20failure\x20shape\x20exactly:\x20a\x20guard\x20meant\x20to\x20fail\
    \x20open\x20turning\n\x20\x20\x20\x20\x20fail-closed\x20under\x20clock\
    \x20arithmetic.\x20Bounding\x20the\x20rejection\x20makes\x20a\x20large\n\
    \x20\x20\x20\x20\x20backwards\x20step\x20self-correcting\x20(the\x20next\
    \x20packet\x20is\x20simply\x20applied)\x20while\n\x20\x20\x20\x20\x20sti\
    ll\x20suppressing\x20genuine\x20reordering.\n\n\x0b\n\x03\x04\0\x01\x12\
    \x04\x89\x01\x08\x1a\n\x9b\x07\n\x04\x04\0\x02\0\x12\x04\x99\x01\x02\x13\
    \x1a\x8c\x07\x20Absolute\x20timer\x20state.\x20true\x20=\x20a\x20timer\
    \x20is\x20running\x20and\x20ends\x20at\x20`ends_at_ms`;\n\x20false\x20=\
    \x20NO\x20timer\x20(never\x20started,\x20cancelled,\x20or\x20cleared).\
    \x20NOT\x20a\x20toggle.\n\n\x20proto3\x20omits\x20default\x20values\x20o\
    n\x20the\x20wire,\x20so\x20a\x20CANCEL\x20serializes\x20to\x20zero\n\x20\
    bytes\x20for\x20this\x20field\x20\xe2\x80\x94\x20which\x20also\x20means\
    \x20an\x20EMPTY\x20or\x20truncated\x20payload\n\x20parses\x20as\x20`runn\
    ing\x20=\x20false`.\x20That\x20degradation\x20is\x20deliberately\x20the\
    \x20SAFE\x20one:\n\x20the\x20worst\x20a\x20corrupt\x20payload\x20can\x20\
    do\x20is\x20clear\x20the\x20timer,\x20never\x20start\x20one\x20and\n\x20\
    never\x20trigger\x20the\x20expiry\x20sound.\n\n\x20WHY\x20THIS\x20FIELD\
    \x20IS\x20NOT\x20REDUNDANT\x20with\x20`ends_at_ms\x20==\x200`:\x20a\x20C\
    ANCELLED\x20timer\n\x20and\x20an\x20EXPIRED\x20timer\x20must\x20be\x20di\
    stinguishable,\x20because\x20they\x20differ\x20in\x20the\n\x20one\x20beh\
    aviour\x20users\x20hear.\x20An\x20expired\x20timer\x20(running\x20=\x20t\
    rue,\x20`ends_at_ms`\x20in\n\x20the\x20past)\x20plays\x20the\x20expiry\
    \x20sound;\x20a\x20cancelled\x20one\x20is\x20silent.\x20With\x20only\x20\
    an\n\x20end\x20instant\x20to\x20go\x20on,\x20a\x20cancel\x20would\x20be\
    \x20indistinguishable\x20from\x20a\x20timer\x20that\n\x20ended\x20at\x20\
    the\x20epoch\x20and\x20every\x20cancel\x20would\x20beep.\n\n\r\n\x05\x04\
    \0\x02\0\x05\x12\x04\x99\x01\x02\x06\n\r\n\x05\x04\0\x02\0\x01\x12\x04\
    \x99\x01\x07\x0e\n\r\n\x05\x04\0\x02\0\x03\x12\x04\x99\x01\x11\x12\n\xa7\
    \x11\n\x04\x04\0\x02\x01\x12\x04\xbd\x01\x02\x18\x1a\x98\x11\x20Unix\x20\
    epoch\x20milliseconds\x20at\x20which\x20the\x20timer\x20reaches\x20zero.\
    \x20Meaningless\x20(send\n\x200)\x20when\x20`running\x20==\x20false`.\n\
    \n\x20Computed\x20ONCE,\x20by\x20the\x20host,\x20at\x20the\x20start/exte\
    nd\x20transition,\x20and\x20preserved\n\x20VERBATIM\x20across\x20every\
    \x20heartbeat\x20and\x20repeat.\x20Never\x20recompute\x20it\x20on\x20a\n\
    \x20re-send:\x20recomputing\x20is\x20what\x20would\x20let\x20a\x20host\
    \x20clock\x20step\x20leak\x20into\x20a\n\x20running\x20timer\x20that\x20\
    viewers\x20had\x20already\x20sampled\x20correctly.\n\n\x20WHICH\x20CLOCK\
    ,\x20AND\x20WHAT\x20THE\x20SKEW\x20COSTS:\x20this\x20is\x20the\x20HOST'S\
    \x20WALL\x20clock\x20(epoch\n\x20ms,\x20so\x20time\x20zones\x20are\x20ir\
    relevant\x20\xe2\x80\x94\x20only\x20absolute\x20offset\x20matters),\x20a\
    nd\x20each\n\x20viewer\x20subtracts\x20its\x20OWN\x20wall\x20clock\x20fr\
    om\x20it.\x20The\x20rendered\x20remaining\x20time\x20is\n\x20therefore\
    \x20off\x20by\x20exactly\x20the\x20host/viewer\x20clock\x20skew.\n\x20\
    \x20\x20*\x20In\x20practice\x20that\x20is\x20nothing.\x20Desktop\x20and\
    \x20mobile\x20OSes\x20are\x20NTP-synced\x20by\n\x20\x20\x20\x20\x20defau\
    lt\x20and\x20hold\x20well\x20under\x20a\x20second\x20of\x20offset;\x20ag\
    ainst\x20a\x20timer\x20measured\n\x20\x20\x20\x20\x20in\x20minutes,\x20a\
    nd\x20rendered\x20at\x201-second\x20granularity,\x20sub-second\x20skew\
    \x20is\x20not\n\x20\x20\x20\x20\x20observable.\x20Even\x20a\x20pathologi\
    cal\x205s\x20of\x20skew\x20on\x20a\x205-minute\x20slot\x20is\x201.7%.\n\
    \x20\x20\x20*\x20It\x20does\x20not\x20accumulate.\x20Skew\x20is\x20sampl\
    ed\x20once\x20at\x20receipt\x20(see\x20wire\n\x20\x20\x20\x20\x20contrac\
    t\x20rule\x204)\x20rather\x20than\x20re-applied\x20on\x20every\x20tick.\
    \n\x20\x20\x20*\x20A\x20client\x20whose\x20clock\x20is\x20wrong\x20by\
    \x20minutes\x20or\x20hours\x20WILL\x20render\x20nonsense\x20\xe2\x80\x94\
    \n\x20\x20\x20\x20\x20but\x20that\x20client\x20already\x20renders\x20eve\
    ry\x20timestamp\x20in\x20the\x20product\x20wrong,\n\x20\x20\x20\x20\x20a\
    nd\x20the\x20failure\x20is\x20confined\x20to\x20its\x20own\x20screen.\n\
    \x20So\x20this\x20is\x20deliberately\x20NOT\x20corrected.\x20The\x20alte\
    rnative\x20\xe2\x80\x94\x20having\x20the\x20relay\n\x20stamp\x20its\x20o\
    wn\x20`now`\x20so\x20viewers\x20could\x20estimate\x20an\x20offset\x20\
    \xe2\x80\x94\x20buys\x20accuracy\x20we\n\x20cannot\x20use\x20(the\x20est\
    imate\x20would\x20fold\x20in\x20an\x20unmeasured\x20one-way\x20network\
    \x20delay,\n\x20and\x20the\x20relay's\x20clock\x20is\x20no\x20more\x20tr\
    ustworthy\x20than\x20the\x20host's)\x20at\x20the\x20cost\x20of\n\x20a\
    \x20clock-offset\x20estimator\x20on\x20every\x20client.\x20If\x20a\x20fu\
    ture\x20need\x20for\x20it\x20appears,\n\x20it\x20is\x20an\x20additive\
    \x20field\x20and\x20this\x20design\x20does\x20not\x20block\x20it.\n\n\
    \x20The\x20relay\x20deliberately\x20performs\x20NO\x20clock\x20arithmeti\
    c\x20on\x20this\x20field:\x20it\x20never\n\x20compares\x20it\x20to\x20th\
    e\x20relay's\x20own\x20clock\x20and\x20never\x20rewrites\x20it.\x20A\x20\
    \"reject\n\x20timers\x20ending\x20too\x20far\x20in\x20the\x20future\"\
    \x20rule\x20would\x20have\x20to\x20read\x20the\x20relay\n\x20clock,\x20a\
    nd\x20a\x20relay\x20clock\x20that\x20stepped\x20backwards\x20would\x20th\
    en\x20start\x20rejecting\n\x20legitimate\x20timers\x20\xe2\x80\x94\x20a\
    \x20fail-closed\x20wedge\x20for\x20no\x20benefit,\x20since\x20the\x20sen\
    der\x20is\n\x20the\x20authorized\x20host\x20and\x20is\x20entitled\x20to\
    \x20set\x20any\x20end\x20time\x20it\x20likes.\n\n\r\n\x05\x04\0\x02\x01\
    \x05\x12\x04\xbd\x01\x02\x08\n\r\n\x05\x04\0\x02\x01\x01\x12\x04\xbd\x01\
    \t\x13\n\r\n\x05\x04\0\x02\x01\x03\x12\x04\xbd\x01\x16\x17\n\x8c\r\n\x04\
    \x04\0\x02\x02\x12\x04\xd9\x01\x02\x19\x1a\xfd\x0c\x20Total\x20span\x20t\
    his\x20timer\x20currently\x20represents,\x20in\x20milliseconds\x20\xe2\
    \x80\x94\x20the\x20duration\n\x20the\x20host\x20configured,\x20INCLUDING\
    \x20any\x20extension\x20(an\x20extend\x20from\x205\x20to\x208\x20minutes\
    \n\x20sets\x208\x20minutes\x20here,\x20not\x203).\x20Meaningless\x20(sen\
    d\x200)\x20when\x20`running\x20==\x20false`.\n\n\x20DISPLAY\x20ONLY.\x20\
    `ends_at_ms`\x20alone\x20is\x20the\x20authoritative\x20countdown;\x20thi\
    s\x20exists\n\x20so\x20a\x20client\x20can\x20render\x20a\x20proportion\
    \x20(a\x20progress\x20ring,\x20\"3:12\x20of\x205:00\")\n\x20without\x20a\
    \x20second\x20clock.\x20It\x20is\x20required\x20rather\x20than\x20option\
    al\x20precisely\n\x20BECAUSE\x20of\x20late\x20joiners:\x20a\x20client\
    \x20that\x20joins\x20mid-run\x20has\x20no\x20way\x20to\x20know\x20the\n\
    \x20timer\x20started\x20at\x20five\x20minutes,\x20so\x20a\x20client-side\
    \x20\"total\"\x20reconstructed\x20from\n\x20first\x20observation\x20woul\
    d\x20be\x20wrong\x20for\x20exactly\x20the\x20clients\x20this\x20design\
    \x20exists\n\x20to\x20serve.\n\n\x20`started_at_ms`\x20is\x20`ends_at_ms\
    \x20-\x20duration_ms`.\x20Compute\x20it\x20with\x20a\x20SATURATING\n\x20\
    subtraction,\x20and\x20likewise\x20for\x20`remaining\x20=\x20ends_at_ms\
    \x20-\x20now`:\x20the\x20relay\n\x20rejects\x20`ends_at_ms\x20<\x20durat\
    ion_ms`\x20at\x20ingress\x20so\x20the\x20first\x20cannot\x20underflow\n\
    \x20from\x20a\x20conforming\x20relay,\x20but\x20a\x20peer\x20may\x20be\
    \x20running\x20an\x20older\x20one,\x20and\x20the\n\x20SECOND\x20underflo\
    ws\x20routinely\x20and\x20by\x20design\x20\xe2\x80\x94\x20every\x20timer\
    \x20that\x20has\x20expired\x20has\n\x20`now\x20>\x20ends_at_ms`.\x20An\
    \x20unguarded\x20`u64`\x20subtraction\x20there\x20panics\x20in\x20a\x20d\
    ebug\n\x20wasm\x20build,\x20which\x20aborts\x20the\x20module\x20and\x20d\
    rops\x20the\x20whole\x20call\x20for\x20that\x20tab.\n\n\x20Bounded\x20at\
    \x20ingress\x20by\x20MEETING_TIMER_MAX_DURATION_MS\x20(24h);\x20an\x20ov\
    er-cap\x20value\n\x20DROPS\x20the\x20packet.\x20That\x20bound\x20is\x20a\
    rithmetic\x20hygiene,\x20not\x20authorization\x20\xe2\x80\x94\x20the\n\
    \x20host\x20is\x20entitled\x20to\x20any\x20duration\x20within\x20it\x20\
    \xe2\x80\x94\x20and\x20it\x20exists\x20so\x20an\x20unbounded\n\x20u64\
    \x20cannot\x20overflow\x20client-side\x20arithmetic.\x20The\x20client\
    \x20MUST\x20clamp\n\x20independently\x20before\x20rendering,\x20exactly\
    \x20as\x20it\x20does\x20for\x20REACTION's\n\x20`custom_emoji`:\x20a\x20p\
    eer\x20may\x20be\x20running\x20an\x20older\x20or\x20newer\x20relay.\n\n\
    \r\n\x05\x04\0\x02\x02\x05\x12\x04\xd9\x01\x02\x08\n\r\n\x05\x04\0\x02\
    \x02\x01\x12\x04\xd9\x01\t\x14\n\r\n\x05\x04\0\x02\x02\x03\x12\x04\xd9\
    \x01\x17\x18\n\xc8\t\n\x04\x04\0\x02\x03\x12\x04\xee\x01\x02\x1b\x1a\xb9\
    \t\x20Unix\x20epoch\x20milliseconds\x20at\x20which\x20the\x20host\x20AUT\
    HORED\x20this\x20state,\x20set\x20once\x20at\n\x20the\x20transition\x20t\
    hat\x20produced\x20it\x20and\x20preserved\x20VERBATIM\x20across\x20every\
    \n\x20heartbeat\x20and\x20repeat\x20of\x20that\x20same\x20state.\x20Re-s\
    tamping\x20it\x20on\x20a\x20re-send\x20would\n\x20destroy\x20the\x20orde\
    ring\x20guarantee\x20it\x20exists\x20to\x20provide.\n\n\x20Its\x20sole\
    \x20consumer\x20is\x20the\x20last-writer-wins\x20comparator\x20in\x20wir\
    e\x20contract\x20rule\n\x20(5),\x20which\x20suppresses\x20a\x20reordered\
    \x20packet\x20on\x20the\x20WebTransport\x20datagram\x20path\n\x20\xe2\
    \x80\x94\x20the\x20case\x20where\x20a\x20stale\x20START\x20could\x20othe\
    rwise\x20land\x20after\x20a\x20CANCEL\x20and\n\x20resurrect\x20a\x20time\
    r\x20the\x20host\x20already\x20stopped.\x20Read\x20rule\x20(5)\x20before\
    \x20writing\n\x20that\x20comparator:\x20it\x20has\x20a\x20bounded\x20rej\
    ection\x20window,\x20and\x20the\x20bound\x20is\x20what\n\x20stops\x20a\
    \x20host\x20clock\x20step\x20from\x20wedging\x20the\x20feature.\n\n\x20S\
    ame\x20trust\x20class\x20as\x20RaiseHandPacket.raised_at_ms:\x20sender\
    \x20wall\x20clock,\n\x20ADVISORY,\x20never\x20authorization.\x20It\x20ca\
    nnot\x20be\x20relay-stamped\x20(a\x20heartbeat\x20would\n\x20then\x20be\
    \x20re-stamped\x20later\x20and\x20defeat\x20the\x20comparator),\x20and\
    \x20it\x20cannot\x20be\x20a\n\x20per-client\x20monotonic\x20clock\x20(th\
    ose\x20have\x20per-tab\x20origins\x20and\x20are\x20not\n\x20comparable\
    \x20across\x20the\x20reconnects\x20this\x20must\x20survive).\x20Forgery\
    \x20is\x20not\x20a\n\x20concern\x20here\x20in\x20the\x20way\x20it\x20is\
    \x20for\x20a\x20raised\x20hand:\x20only\x20the\x20host\x20can\x20send\
    \x20this\n\x20packet\x20at\x20all,\x20and\x20the\x20host\x20can\x20alrea\
    dy\x20author\x20any\x20state\x20it\x20wants.\n\n\r\n\x05\x04\0\x02\x03\
    \x05\x12\x04\xee\x01\x02\x08\n\r\n\x05\x04\0\x02\x03\x01\x12\x04\xee\x01\
    \t\x16\n\r\n\x05\x04\0\x02\x03\x03\x12\x04\xee\x01\x19\x1ab\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(MeetingTimerPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
