// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/packet_wrapper.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:PacketWrapper)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PacketWrapper {
    // message fields
    // @@protoc_insertion_point(field:PacketWrapper.packet_type)
    pub packet_type: ::protobuf::EnumOrUnknown<packet_wrapper::PacketType>,
    // @@protoc_insertion_point(field:PacketWrapper.user_id)
    pub user_id: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:PacketWrapper.data)
    pub data: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:PacketWrapper.session_id)
    pub session_id: u64,
    ///  Simulcast layer id (#989/PR #993); see discussion #890.
    // @@protoc_insertion_point(field:PacketWrapper.simulcast_layer_id)
    pub simulcast_layer_id: u32,
    ///  Cleartext discriminator; see MediaKind. Default 0 = unspecified = fail-open.
    // @@protoc_insertion_point(field:PacketWrapper.media_kind)
    pub media_kind: ::protobuf::EnumOrUnknown<packet_wrapper::MediaKind>,
    // special fields
    // @@protoc_insertion_point(special_field:PacketWrapper.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PacketWrapper {
    fn default() -> &'a PacketWrapper {
        <PacketWrapper as ::protobuf::Message>::default_instance()
    }
}

impl PacketWrapper {
    pub fn new() -> PacketWrapper {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "packet_type",
            |m: &PacketWrapper| { &m.packet_type },
            |m: &mut PacketWrapper| { &mut m.packet_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "user_id",
            |m: &PacketWrapper| { &m.user_id },
            |m: &mut PacketWrapper| { &mut m.user_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &PacketWrapper| { &m.data },
            |m: &mut PacketWrapper| { &mut m.data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "session_id",
            |m: &PacketWrapper| { &m.session_id },
            |m: &mut PacketWrapper| { &mut m.session_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "simulcast_layer_id",
            |m: &PacketWrapper| { &m.simulcast_layer_id },
            |m: &mut PacketWrapper| { &mut m.simulcast_layer_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "media_kind",
            |m: &PacketWrapper| { &m.media_kind },
            |m: &mut PacketWrapper| { &mut m.media_kind },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PacketWrapper>(
            "PacketWrapper",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PacketWrapper {
    const NAME: &'static str = "PacketWrapper";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.packet_type = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.user_id = is.read_bytes()?;
                },
                26 => {
                    self.data = is.read_bytes()?;
                },
                32 => {
                    self.session_id = is.read_uint64()?;
                },
                40 => {
                    self.simulcast_layer_id = is.read_uint32()?;
                },
                48 => {
                    self.media_kind = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.packet_type != ::protobuf::EnumOrUnknown::new(packet_wrapper::PacketType::PACKET_TYPE_UNKNOWN) {
            my_size += ::protobuf::rt::int32_size(1, self.packet_type.value());
        }
        if !self.user_id.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.user_id);
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.data);
        }
        if self.session_id != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.session_id);
        }
        if self.simulcast_layer_id != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.simulcast_layer_id);
        }
        if self.media_kind != ::protobuf::EnumOrUnknown::new(packet_wrapper::MediaKind::MEDIA_KIND_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(6, self.media_kind.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.packet_type != ::protobuf::EnumOrUnknown::new(packet_wrapper::PacketType::PACKET_TYPE_UNKNOWN) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.packet_type))?;
        }
        if !self.user_id.is_empty() {
            os.write_bytes(2, &self.user_id)?;
        }
        if !self.data.is_empty() {
            os.write_bytes(3, &self.data)?;
        }
        if self.session_id != 0 {
            os.write_uint64(4, self.session_id)?;
        }
        if self.simulcast_layer_id != 0 {
            os.write_uint32(5, self.simulcast_layer_id)?;
        }
        if self.media_kind != ::protobuf::EnumOrUnknown::new(packet_wrapper::MediaKind::MEDIA_KIND_UNSPECIFIED) {
            os.write_enum(6, ::protobuf::EnumOrUnknown::value(&self.media_kind))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PacketWrapper {
        PacketWrapper::new()
    }

    fn clear(&mut self) {
        self.packet_type = ::protobuf::EnumOrUnknown::new(packet_wrapper::PacketType::PACKET_TYPE_UNKNOWN);
        self.user_id.clear();
        self.data.clear();
        self.session_id = 0;
        self.simulcast_layer_id = 0;
        self.media_kind = ::protobuf::EnumOrUnknown::new(packet_wrapper::MediaKind::MEDIA_KIND_UNSPECIFIED);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PacketWrapper {
        static instance: PacketWrapper = PacketWrapper {
            packet_type: ::protobuf::EnumOrUnknown::from_i32(0),
            user_id: ::std::vec::Vec::new(),
            data: ::std::vec::Vec::new(),
            session_id: 0,
            simulcast_layer_id: 0,
            media_kind: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PacketWrapper {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PacketWrapper").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PacketWrapper {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PacketWrapper {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `PacketWrapper`
pub mod packet_wrapper {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:PacketWrapper.PacketType)
    pub enum PacketType {
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.PACKET_TYPE_UNKNOWN)
        PACKET_TYPE_UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.RSA_PUB_KEY)
        RSA_PUB_KEY = 1,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.AES_KEY)
        AES_KEY = 2,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.MEDIA)
        MEDIA = 3,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.CONNECTION)
        CONNECTION = 4,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.DIAGNOSTICS)
        DIAGNOSTICS = 5,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.HEALTH)
        HEALTH = 6,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.MEETING)
        MEETING = 7,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.SESSION_ASSIGNED)
        SESSION_ASSIGNED = 8,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.CONGESTION)
        CONGESTION = 9,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.PEER_EVENT)
        PEER_EVENT = 10,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.VIEWPORT)
        VIEWPORT = 11,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.LAYER_PREFERENCE)
        LAYER_PREFERENCE = 12,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.LAYER_HINT)
        LAYER_HINT = 13,
        // @@protoc_insertion_point(enum_value:PacketWrapper.PacketType.DOWNLINK_CONGESTION)
        DOWNLINK_CONGESTION = 14,
    }

    impl ::protobuf::Enum for PacketType {
        const NAME: &'static str = "PacketType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<PacketType> {
            match value {
                0 => ::std::option::Option::Some(PacketType::PACKET_TYPE_UNKNOWN),
                1 => ::std::option::Option::Some(PacketType::RSA_PUB_KEY),
                2 => ::std::option::Option::Some(PacketType::AES_KEY),
                3 => ::std::option::Option::Some(PacketType::MEDIA),
                4 => ::std::option::Option::Some(PacketType::CONNECTION),
                5 => ::std::option::Option::Some(PacketType::DIAGNOSTICS),
                6 => ::std::option::Option::Some(PacketType::HEALTH),
                7 => ::std::option::Option::Some(PacketType::MEETING),
                8 => ::std::option::Option::Some(PacketType::SESSION_ASSIGNED),
                9 => ::std::option::Option::Some(PacketType::CONGESTION),
                10 => ::std::option::Option::Some(PacketType::PEER_EVENT),
                11 => ::std::option::Option::Some(PacketType::VIEWPORT),
                12 => ::std::option::Option::Some(PacketType::LAYER_PREFERENCE),
                13 => ::std::option::Option::Some(PacketType::LAYER_HINT),
                14 => ::std::option::Option::Some(PacketType::DOWNLINK_CONGESTION),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<PacketType> {
            match str {
                "PACKET_TYPE_UNKNOWN" => ::std::option::Option::Some(PacketType::PACKET_TYPE_UNKNOWN),
                "RSA_PUB_KEY" => ::std::option::Option::Some(PacketType::RSA_PUB_KEY),
                "AES_KEY" => ::std::option::Option::Some(PacketType::AES_KEY),
                "MEDIA" => ::std::option::Option::Some(PacketType::MEDIA),
                "CONNECTION" => ::std::option::Option::Some(PacketType::CONNECTION),
                "DIAGNOSTICS" => ::std::option::Option::Some(PacketType::DIAGNOSTICS),
                "HEALTH" => ::std::option::Option::Some(PacketType::HEALTH),
                "MEETING" => ::std::option::Option::Some(PacketType::MEETING),
                "SESSION_ASSIGNED" => ::std::option::Option::Some(PacketType::SESSION_ASSIGNED),
                "CONGESTION" => ::std::option::Option::Some(PacketType::CONGESTION),
                "PEER_EVENT" => ::std::option::Option::Some(PacketType::PEER_EVENT),
                "VIEWPORT" => ::std::option::Option::Some(PacketType::VIEWPORT),
                "LAYER_PREFERENCE" => ::std::option::Option::Some(PacketType::LAYER_PREFERENCE),
                "LAYER_HINT" => ::std::option::Option::Some(PacketType::LAYER_HINT),
                "DOWNLINK_CONGESTION" => ::std::option::Option::Some(PacketType::DOWNLINK_CONGESTION),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [PacketType] = &[
            PacketType::PACKET_TYPE_UNKNOWN,
            PacketType::RSA_PUB_KEY,
            PacketType::AES_KEY,
            PacketType::MEDIA,
            PacketType::CONNECTION,
            PacketType::DIAGNOSTICS,
            PacketType::HEALTH,
            PacketType::MEETING,
            PacketType::SESSION_ASSIGNED,
            PacketType::CONGESTION,
            PacketType::PEER_EVENT,
            PacketType::VIEWPORT,
            PacketType::LAYER_PREFERENCE,
            PacketType::LAYER_HINT,
            PacketType::DOWNLINK_CONGESTION,
        ];
    }

    impl ::protobuf::EnumFull for PacketType {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("PacketWrapper.PacketType").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for PacketType {
        fn default() -> Self {
            PacketType::PACKET_TYPE_UNKNOWN
        }
    }

    impl PacketType {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<PacketType>("PacketWrapper.PacketType")
        }
    }

    ///  Cleartext media-kind discriminator on the OUTER envelope.
    ///
    ///  Under E2EE_ENABLED=true the inner MediaPacket (including its own
    ///  `media_type`) is AES-sealed, so the relay — which never decrypts —
    ///  cannot tell VIDEO from AUDIO/SCREEN. This field lets the publisher
    ///  advertise the media kind in cleartext so the relay can apply
    ///  viewport-aware VIDEO filtering while ALWAYS forwarding AUDIO.
    ///
    ///  Set only by the publishing client on MEDIA packets. Other packet
    ///  types leave it unspecified. The default (UNSPECIFIED = 0) MUST be
    ///  treated as fail-open (forward) by the relay so that older clients,
    ///  non-media packets, and any future packet type keep working unchanged.
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:PacketWrapper.MediaKind)
    pub enum MediaKind {
        // @@protoc_insertion_point(enum_value:PacketWrapper.MediaKind.MEDIA_KIND_UNSPECIFIED)
        MEDIA_KIND_UNSPECIFIED = 0,
        // @@protoc_insertion_point(enum_value:PacketWrapper.MediaKind.VIDEO)
        VIDEO = 1,
        // @@protoc_insertion_point(enum_value:PacketWrapper.MediaKind.AUDIO)
        AUDIO = 2,
        // @@protoc_insertion_point(enum_value:PacketWrapper.MediaKind.SCREEN)
        SCREEN = 3,
    }

    impl ::protobuf::Enum for MediaKind {
        const NAME: &'static str = "MediaKind";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<MediaKind> {
            match value {
                0 => ::std::option::Option::Some(MediaKind::MEDIA_KIND_UNSPECIFIED),
                1 => ::std::option::Option::Some(MediaKind::VIDEO),
                2 => ::std::option::Option::Some(MediaKind::AUDIO),
                3 => ::std::option::Option::Some(MediaKind::SCREEN),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<MediaKind> {
            match str {
                "MEDIA_KIND_UNSPECIFIED" => ::std::option::Option::Some(MediaKind::MEDIA_KIND_UNSPECIFIED),
                "VIDEO" => ::std::option::Option::Some(MediaKind::VIDEO),
                "AUDIO" => ::std::option::Option::Some(MediaKind::AUDIO),
                "SCREEN" => ::std::option::Option::Some(MediaKind::SCREEN),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [MediaKind] = &[
            MediaKind::MEDIA_KIND_UNSPECIFIED,
            MediaKind::VIDEO,
            MediaKind::AUDIO,
            MediaKind::SCREEN,
        ];
    }

    impl ::protobuf::EnumFull for MediaKind {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("PacketWrapper.MediaKind").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for MediaKind {
        fn default() -> Self {
            MediaKind::MEDIA_KIND_UNSPECIFIED
        }
    }

    impl MediaKind {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<MediaKind>("PacketWrapper.MediaKind")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1atypes/packet_wrapper.proto\"\xd7\x04\n\rPacketWrapper\x12:\n\x0bpa\
    cket_type\x18\x01\x20\x01(\x0e2\x19.PacketWrapper.PacketTypeR\npacketTyp\
    e\x12\x17\n\x07user_id\x18\x02\x20\x01(\x0cR\x06userId\x12\x12\n\x04data\
    \x18\x03\x20\x01(\x0cR\x04data\x12\x1d\n\nsession_id\x18\x04\x20\x01(\
    \x04R\tsessionId\x12,\n\x12simulcast_layer_id\x18\x05\x20\x01(\rR\x10sim\
    ulcastLayerId\x127\n\nmedia_kind\x18\x06\x20\x01(\x0e2\x18.PacketWrapper\
    .MediaKindR\tmediaKind\"\x8b\x02\n\nPacketType\x12\x17\n\x13PACKET_TYPE_\
    UNKNOWN\x10\0\x12\x0f\n\x0bRSA_PUB_KEY\x10\x01\x12\x0b\n\x07AES_KEY\x10\
    \x02\x12\t\n\x05MEDIA\x10\x03\x12\x0e\n\nCONNECTION\x10\x04\x12\x0f\n\
    \x0bDIAGNOSTICS\x10\x05\x12\n\n\x06HEALTH\x10\x06\x12\x0b\n\x07MEETING\
    \x10\x07\x12\x14\n\x10SESSION_ASSIGNED\x10\x08\x12\x0e\n\nCONGESTION\x10\
    \t\x12\x0e\n\nPEER_EVENT\x10\n\x12\x0c\n\x08VIEWPORT\x10\x0b\x12\x14\n\
    \x10LAYER_PREFERENCE\x10\x0c\x12\x0e\n\nLAYER_HINT\x10\r\x12\x17\n\x13DO\
    WNLINK_CONGESTION\x10\x0e\"I\n\tMediaKind\x12\x1a\n\x16MEDIA_KIND_UNSPEC\
    IFIED\x10\0\x12\t\n\x05VIDEO\x10\x01\x12\t\n\x05AUDIO\x10\x02\x12\n\n\
    \x06SCREEN\x10\x03J\xc9$\n\x06\x12\x04\0\0V\x01\n\x08\n\x01\x0c\x12\x03\
    \0\0\x12\n\n\n\x02\x04\0\x12\x04\x02\0V\x01\n\n\n\x03\x04\0\x01\x12\x03\
    \x02\x08\x15\n\x0c\n\x04\x04\0\x04\0\x12\x04\x03\x029\x03\n\x0c\n\x05\
    \x04\0\x04\0\x01\x12\x03\x03\x07\x11\n\r\n\x06\x04\0\x04\0\x02\0\x12\x03\
    \x04\x04\x1c\n\x0e\n\x07\x04\0\x04\0\x02\0\x01\x12\x03\x04\x04\x17\n\x0e\
    \n\x07\x04\0\x04\0\x02\0\x02\x12\x03\x04\x1a\x1b\n\r\n\x06\x04\0\x04\0\
    \x02\x01\x12\x03\x05\x04\x14\n\x0e\n\x07\x04\0\x04\0\x02\x01\x01\x12\x03\
    \x05\x04\x0f\n\x0e\n\x07\x04\0\x04\0\x02\x01\x02\x12\x03\x05\x12\x13\n\r\
    \n\x06\x04\0\x04\0\x02\x02\x12\x03\x06\x04\x10\n\x0e\n\x07\x04\0\x04\0\
    \x02\x02\x01\x12\x03\x06\x04\x0b\n\x0e\n\x07\x04\0\x04\0\x02\x02\x02\x12\
    \x03\x06\x0e\x0f\n\r\n\x06\x04\0\x04\0\x02\x03\x12\x03\x07\x04\x0e\n\x0e\
    \n\x07\x04\0\x04\0\x02\x03\x01\x12\x03\x07\x04\t\n\x0e\n\x07\x04\0\x04\0\
    \x02\x03\x02\x12\x03\x07\x0c\r\n\r\n\x06\x04\0\x04\0\x02\x04\x12\x03\x08\
    \x04\x13\n\x0e\n\x07\x04\0\x04\0\x02\x04\x01\x12\x03\x08\x04\x0e\n\x0e\n\
    \x07\x04\0\x04\0\x02\x04\x02\x12\x03\x08\x11\x12\n\r\n\x06\x04\0\x04\0\
    \x02\x05\x12\x03\t\x04\x14\n\x0e\n\x07\x04\0\x04\0\x02\x05\x01\x12\x03\t\
    \x04\x0f\n\x0e\n\x07\x04\0\x04\0\x02\x05\x02\x12\x03\t\x12\x13\n\r\n\x06\
    \x04\0\x04\0\x02\x06\x12\x03\n\x04\x0f\n\x0e\n\x07\x04\0\x04\0\x02\x06\
    \x01\x12\x03\n\x04\n\n\x0e\n\x07\x04\0\x04\0\x02\x06\x02\x12\x03\n\r\x0e\
    \n\r\n\x06\x04\0\x04\0\x02\x07\x12\x03\x0b\x04\x10\n\x0e\n\x07\x04\0\x04\
    \0\x02\x07\x01\x12\x03\x0b\x04\x0b\n\x0e\n\x07\x04\0\x04\0\x02\x07\x02\
    \x12\x03\x0b\x0e\x0f\n\r\n\x06\x04\0\x04\0\x02\x08\x12\x03\x0c\x04\x19\n\
    \x0e\n\x07\x04\0\x04\0\x02\x08\x01\x12\x03\x0c\x04\x14\n\x0e\n\x07\x04\0\
    \x04\0\x02\x08\x02\x12\x03\x0c\x17\x18\n\r\n\x06\x04\0\x04\0\x02\t\x12\
    \x03\r\x04\x13\n\x0e\n\x07\x04\0\x04\0\x02\t\x01\x12\x03\r\x04\x0e\n\x0e\
    \n\x07\x04\0\x04\0\x02\t\x02\x12\x03\r\x11\x12\n\r\n\x06\x04\0\x04\0\x02\
    \n\x12\x03\x0e\x04\x14\n\x0e\n\x07\x04\0\x04\0\x02\n\x01\x12\x03\x0e\x04\
    \x0e\n\x0e\n\x07\x04\0\x04\0\x02\n\x02\x12\x03\x0e\x11\x13\n\xa0\x02\n\
    \x06\x04\0\x04\0\x02\x0b\x12\x03\x13\x04\x12\x1a\x90\x02\x20Client\x20->\
    \x20relay\x20ONLY\x20control\x20packet.\x20Carries\x20the\x20set\x20of\
    \x20session_ids\n\x20the\x20sender\x20is\x20currently\x20rendering\x20(i\
    ts\x20viewport\x20/\x20\"desired\x20streams\"\n\x20set).\x20The\x20relay\
    \x20consumes\x20this\x20to\x20filter\x20VIDEO\x20it\x20forwards\x20downs\
    tream\n\x20(see\x20ViewportPacket).\x20It\x20is\x20never\x20re-broadcast\
    \x20to\x20other\x20peers.\n\n\x0e\n\x07\x04\0\x04\0\x02\x0b\x01\x12\x03\
    \x13\x04\x0c\n\x0e\n\x07\x04\0\x04\0\x02\x0b\x02\x12\x03\x13\x0f\x11\n\
    \xf1\x03\n\x06\x04\0\x04\0\x02\x0c\x12\x03\x1b\x04\x1a\x1a\xe1\x03\x20Cl\
    ient\x20->\x20relay\x20ONLY\x20control\x20packet\x20(#989,\x20Phase\x201\
    b).\x20Carries\x20the\n\x20per-sender\x20simulcast\x20layer\x20each\x20r\
    eceiver\x20wants\x20the\x20relay\x20to\x20forward\n\x20(its\x20\"layer\
    \x20preferences\").\x20The\x20relay\x20consumes\x20this\x20to\x20drop\
    \x20simulcast\n\x20VIDEO\x20layers\x20the\x20receiver\x20did\x20not\x20s\
    elect\x20(see\x20LayerPreferencePacket).\n\x20It\x20is\x20never\x20re-br\
    oadcast\x20to\x20other\x20peers,\x20and\x20\xe2\x80\x94\x20like\x20VIEWP\
    ORT\x20\xe2\x80\x94\x20it\x20is\n\x20recorded\x20ONLY\x20when\x20it\x20a\
    rrives\x20on\x20the\x20receiver's\x20own\x20NATS\x20subject,\x20so\x20a\
    \n\x20forged\x20payload\x20only\x20self-degrades\x20the\x20forger's\x20O\
    WN\x20view.\n\n\x0e\n\x07\x04\0\x04\0\x02\x0c\x01\x12\x03\x1b\x04\x14\n\
    \x0e\n\x07\x04\0\x04\0\x02\x0c\x02\x12\x03\x1b\x17\x19\n\x8c\n\n\x06\x04\
    \0\x04\0\x02\r\x12\x030\x04\x14\x1a\xfc\t\x20Relay\x20->\x20publisher\
    \x20ONLY\x20control\x20packet\x20(#1108,\x20Stage\x203).\x20This\x20is\
    \x20the\n\x20mirror\x20image\x20of\x20LAYER_PREFERENCE:\x20where\x20LAYE\
    R_PREFERENCE\x20flows\x20UP\x20from\x20a\n\x20receiver\x20to\x20constrai\
    n\x20what\x20the\x20relay\x20FORWARDS,\x20LAYER_HINT\x20flows\x20DOWN\
    \x20from\n\x20the\x20relay\x20to\x20a\x20single\x20publisher\x20to\x20hi\
    nt\x20what\x20it\x20should\x20bother\x20ENCODING.\n\x20The\x20relay\x20c\
    omputes,\x20per\x20source,\x20the\x20UNION\x20(max)\x20of\x20every\x20re\
    ceiver's\n\x20requested\x20layer\x20for\x20that\x20source\x20and,\x20whe\
    n\x20NO\x20receiver\x20wants\x20a\x20given\x20upper\n\x20layer,\x20hints\
    \x20the\x20publisher\x20to\x20stop\x20producing\x20it\x20(publish-side\n\
    \x20suppression).\x20See\x20LayerHintPacket.\n\n\x20TRUST\x20BOUNDARY\
    \x20(security-critical,\x20inverse\x20of\x20LAYER_PREFERENCE):\x20this\n\
    \x20packet\x20is\x20RELAY-AUTHORED\x20and\x20travels\x20relay\x20->\x20p\
    ublisher\x20ONLY.\x20It\x20is\n\x20delivered\x20on\x20the\x20publisher's\
    \x20OWN\x20per-session\x20NATS\x20subject\n\x20(room.{room}.{publisher_s\
    ession})\x20exactly\x20like\x20the\x20server-authored\n\x20CONGESTION\
    \x20self-packet.\x20The\x20relay\x20NEVER\x20accepts\x20a\x20LAYER_HINT\
    \x20from\x20a\n\x20client:\x20there\x20is\x20no\x20inbound\x20LAYER_HINT\
    \x20ingest\x20path,\x20no\n\x20try_intercept_layer_hint,\x20and\x20no\
    \x20handler\x20that\x20records\x20or\x20acts\x20on\x20a\n\x20LAYER_HINT\
    \x20arriving\x20on\x20a\x20session\x20subject.\x20A\x20client\x20that\
    \x20forges\x20one\x20only\n\x20sends\x20bytes\x20the\x20relay\x20drops\
    \x20on\x20the\x20floor.\x20The\x20hint\x20is\x20purely\x20ADVISORY\x20\
    \xe2\x80\x94\n\x20the\x20publisher\x20clamps\x20it\x20against\x20its\x20\
    own\x20real\x20ladder\x20and\x20a\x20missing/garbage\n\x20hint\x20simply\
    \x20means\x20\"encode\x20the\x20full\x20ladder\"\x20(fail-open).\n\n\x0e\
    \n\x07\x04\0\x04\0\x02\r\x01\x12\x030\x04\x0e\n\x0e\n\x07\x04\0\x04\0\
    \x02\r\x02\x12\x030\x11\x13\n\x8c\x04\n\x06\x04\0\x04\0\x02\x0e\x12\x038\
    \x04\x1d\x1a\xfc\x03\x20Relay\x20->\x20receiver\x20ONLY\x20control\x20pa\
    cket\x20(#1219\x20Half\x202).\x20Signals\x20a\x20receiver\n\x20that\x20i\
    ts\x20downlink\x20is\x20congested\x20(the\x20relay's\x20inbound\x20fan-o\
    ut\x20mailbox\x20is\n\x20dropping\x20packets\x20destined\x20for\x20this\
    \x20session).\x20The\x20receiver\x20should\x20reduce\n\x20its\x20layer\
    \x20preferences\x20to\x20adapt\x20to\x20available\x20bandwidth.\x20Deliv\
    ered\x20on\x20the\n\x20receiver's\x20OWN\x20per-session\x20subject,\x20l\
    ike\x20CONGESTION\x20and\x20LAYER_HINT.\n\x20Unlike\x20CONGESTION\x20(wh\
    ich\x20was\x20sender-directed),\x20this\x20is\x20RECEIVER-directed:\n\
    \x20the\x20slow\x20receiver\x20itself\x20must\x20step\x20down.\x20See\
    \x20DownlinkCongestionPacket.\n\n\x0e\n\x07\x04\0\x04\0\x02\x0e\x01\x12\
    \x038\x04\x17\n\x0e\n\x07\x04\0\x04\0\x02\x0e\x02\x12\x038\x1a\x1c\n\xa7\
    \x05\n\x04\x04\0\x04\x01\x12\x04G\x02L\x03\x1a\x98\x05\x20Cleartext\x20m\
    edia-kind\x20discriminator\x20on\x20the\x20OUTER\x20envelope.\n\n\x20Und\
    er\x20E2EE_ENABLED=true\x20the\x20inner\x20MediaPacket\x20(including\x20\
    its\x20own\n\x20`media_type`)\x20is\x20AES-sealed,\x20so\x20the\x20relay\
    \x20\xe2\x80\x94\x20which\x20never\x20decrypts\x20\xe2\x80\x94\n\x20cann\
    ot\x20tell\x20VIDEO\x20from\x20AUDIO/SCREEN.\x20This\x20field\x20lets\
    \x20the\x20publisher\n\x20advertise\x20the\x20media\x20kind\x20in\x20cle\
    artext\x20so\x20the\x20relay\x20can\x20apply\n\x20viewport-aware\x20VIDE\
    O\x20filtering\x20while\x20ALWAYS\x20forwarding\x20AUDIO.\n\n\x20Set\x20\
    only\x20by\x20the\x20publishing\x20client\x20on\x20MEDIA\x20packets.\x20\
    Other\x20packet\n\x20types\x20leave\x20it\x20unspecified.\x20The\x20defa\
    ult\x20(UNSPECIFIED\x20=\x200)\x20MUST\x20be\n\x20treated\x20as\x20fail-\
    open\x20(forward)\x20by\x20the\x20relay\x20so\x20that\x20older\x20client\
    s,\n\x20non-media\x20packets,\x20and\x20any\x20future\x20packet\x20type\
    \x20keep\x20working\x20unchanged.\n\n\x0c\n\x05\x04\0\x04\x01\x01\x12\
    \x03G\x07\x10\n\r\n\x06\x04\0\x04\x01\x02\0\x12\x03H\x04\x1f\n\x0e\n\x07\
    \x04\0\x04\x01\x02\0\x01\x12\x03H\x04\x1a\n\x0e\n\x07\x04\0\x04\x01\x02\
    \0\x02\x12\x03H\x1d\x1e\n\r\n\x06\x04\0\x04\x01\x02\x01\x12\x03I\x04\x0e\
    \n\x0e\n\x07\x04\0\x04\x01\x02\x01\x01\x12\x03I\x04\t\n\x0e\n\x07\x04\0\
    \x04\x01\x02\x01\x02\x12\x03I\x0c\r\n\r\n\x06\x04\0\x04\x01\x02\x02\x12\
    \x03J\x04\x0e\n\x0e\n\x07\x04\0\x04\x01\x02\x02\x01\x12\x03J\x04\t\n\x0e\
    \n\x07\x04\0\x04\x01\x02\x02\x02\x12\x03J\x0c\r\n\r\n\x06\x04\0\x04\x01\
    \x02\x03\x12\x03K\x04\x0f\n\x0e\n\x07\x04\0\x04\x01\x02\x03\x01\x12\x03K\
    \x04\n\n\x0e\n\x07\x04\0\x04\x01\x02\x03\x02\x12\x03K\r\x0e\n\x0b\n\x04\
    \x04\0\x02\0\x12\x03N\x02\x1d\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03N\x02\
    \x0c\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03N\r\x18\n\x0c\n\x05\x04\0\x02\0\
    \x03\x12\x03N\x1b\x1c\n\x0b\n\x04\x04\0\x02\x01\x12\x03O\x02\x14\n\x0c\n\
    \x05\x04\0\x02\x01\x05\x12\x03O\x02\x07\n\x0c\n\x05\x04\0\x02\x01\x01\
    \x12\x03O\x08\x0f\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03O\x12\x13\n\x0b\n\
    \x04\x04\0\x02\x02\x12\x03P\x02\x11\n\x0c\n\x05\x04\0\x02\x02\x05\x12\
    \x03P\x02\x07\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03P\x08\x0c\n\x0c\n\x05\
    \x04\0\x02\x02\x03\x12\x03P\x0f\x10\n\x0b\n\x04\x04\0\x02\x03\x12\x03Q\
    \x02\x18\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03Q\x02\x08\n\x0c\n\x05\x04\
    \0\x02\x03\x01\x12\x03Q\t\x13\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03Q\x16\
    \x17\nF\n\x04\x04\0\x02\x04\x12\x03S\x02\x20\x1a9\x20Simulcast\x20layer\
    \x20id\x20(#989/PR\x20#993);\x20see\x20discussion\x20#890.\n\n\x0c\n\x05\
    \x04\0\x02\x04\x05\x12\x03S\x02\x08\n\x0c\n\x05\x04\0\x02\x04\x01\x12\
    \x03S\t\x1b\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03S\x1e\x1f\n[\n\x04\x04\
    \0\x02\x05\x12\x03U\x02\x1b\x1aN\x20Cleartext\x20discriminator;\x20see\
    \x20MediaKind.\x20Default\x200\x20=\x20unspecified\x20=\x20fail-open.\n\
    \n\x0c\n\x05\x04\0\x02\x05\x06\x12\x03U\x02\x0b\n\x0c\n\x05\x04\0\x02\
    \x05\x01\x12\x03U\x0c\x16\n\x0c\n\x05\x04\0\x02\x05\x03\x12\x03U\x19\x1a\
    b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(PacketWrapper::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(packet_wrapper::PacketType::generated_enum_descriptor_data());
            enums.push(packet_wrapper::MediaKind::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
