// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/raise_hand_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:RaiseHandPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RaiseHandPacket {
    // message fields
    ///  Absolute hand state. true = raised, false = lowered. NOT a toggle.
    ///
    ///  proto3 omits default values on the wire, so a LOWER serializes to zero
    ///  bytes for this field -- which also means an EMPTY or truncated payload
    ///  parses as `raised = false`. That degradation is deliberately the SAFE one:
    ///  combined with the relay-stamped envelope session_id, the worst a corrupt
    ///  or forged payload can do is lower the SENDER'S OWN hand.
    // @@protoc_insertion_point(field:RaiseHandPacket.raised)
    pub raised: bool,
    // @@protoc_insertion_point(field:RaiseHandPacket.raised_at_ms)
    pub raised_at_ms: u64,
    ///  Cosmetic display-name fallback for the pre-join display-name-cache race
    ///  (a re-announce can outrun the joiner's PARTICIPANT_JOINED list reply).
    ///  SAME threat model and cap as ReactionPacket.display_name: attacker-
    ///  controlled, so the relay bounds it at ingress (<=256 bytes, truncated at a
    ///  UTF-8 char boundary) and the client renders it as ESCAPED text with its own
    ///  <=64-char cap. Authoritative attribution is the relay-stamped envelope
    ///  session_id resolved through the display-name cache; this is only what to
    ///  show while that cache has no entry yet. Optional.
    // @@protoc_insertion_point(field:RaiseHandPacket.display_name)
    pub display_name: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:RaiseHandPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RaiseHandPacket {
    fn default() -> &'a RaiseHandPacket {
        <RaiseHandPacket as ::protobuf::Message>::default_instance()
    }
}

impl RaiseHandPacket {
    pub fn new() -> RaiseHandPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "raised",
            |m: &RaiseHandPacket| { &m.raised },
            |m: &mut RaiseHandPacket| { &mut m.raised },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "raised_at_ms",
            |m: &RaiseHandPacket| { &m.raised_at_ms },
            |m: &mut RaiseHandPacket| { &mut m.raised_at_ms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "display_name",
            |m: &RaiseHandPacket| { &m.display_name },
            |m: &mut RaiseHandPacket| { &mut m.display_name },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RaiseHandPacket>(
            "RaiseHandPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RaiseHandPacket {
    const NAME: &'static str = "RaiseHandPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.raised = is.read_bool()?;
                },
                16 => {
                    self.raised_at_ms = is.read_uint64()?;
                },
                26 => {
                    self.display_name = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.raised != false {
            my_size += 1 + 1;
        }
        if self.raised_at_ms != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.raised_at_ms);
        }
        if !self.display_name.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.display_name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.raised != false {
            os.write_bool(1, self.raised)?;
        }
        if self.raised_at_ms != 0 {
            os.write_uint64(2, self.raised_at_ms)?;
        }
        if !self.display_name.is_empty() {
            os.write_bytes(3, &self.display_name)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RaiseHandPacket {
        RaiseHandPacket::new()
    }

    fn clear(&mut self) {
        self.raised = false;
        self.raised_at_ms = 0;
        self.display_name.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RaiseHandPacket {
        static instance: RaiseHandPacket = RaiseHandPacket {
            raised: false,
            raised_at_ms: 0,
            display_name: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RaiseHandPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RaiseHandPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RaiseHandPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RaiseHandPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1dtypes/raise_hand_packet.proto\"n\n\x0fRaiseHandPacket\x12\x16\n\
    \x06raised\x18\x01\x20\x01(\x08R\x06raised\x12\x20\n\x0craised_at_ms\x18\
    \x02\x20\x01(\x04R\nraisedAtMs\x12!\n\x0cdisplay_name\x18\x03\x20\x01(\
    \x0cR\x0bdisplayNameJ\x95*\n\x06\x12\x04\0\0X\x01\n\x08\n\x01\x0c\x12\
    \x03\0\0\x12\n\x8d\x14\n\x02\x04\0\x12\x04*\0X\x01\x1a\x80\x14\x20Client\
    \x20->\x20relay\x20->\x20all-peers\x20RAISED-HAND\x20STATE\x20broadcast\
    \x20(issue\x20#2135).\n\x20Carried\x20inside\x20a\x20PacketWrapper\x20wh\
    ose\x20packet_type\x20is\x20RAISE_HAND\x20(18).\n\n\x20STATE,\x20NOT\x20\
    AN\x20EVENT\x20--\x20the\x20one\x20property\x20that\x20shapes\x20everyth\
    ing\x20below.\n\x20`raised`\x20is\x20an\x20absolute\x20level\x20(\"my\
    \x20hand\x20is\x20up\x20/\x20down\"),\x20never\x20a\x20toggle,\x20so\n\
    \x20re-sending\x20the\x20SAME\x20value\x20is\x20a\x20harmless\x20no-op\
    \x20for\x20every\x20consumer.\x20That\n\x20idempotence\x20is\x20what\x20\
    makes\x20the\x20RE-ANNOUNCE\x20protocol\x20safe\x20(see\x20below),\x20an\
    d\x20it\n\x20is\x20why\x20the\x20relay\x20can\x20stay\x20a\x20dumb\x20fo\
    rwarder\x20with\x20NO\x20server-side\x20hand\x20registry.\n\x20A\x20togg\
    le-shaped\x20message\x20would\x20make\x20a\x20single\x20lost\x20or\x20du\
    plicated\x20packet\x20invert\n\x20the\x20room's\x20view\x20of\x20a\x20pa\
    rticipant\x20permanently;\x20a\x20level\x20cannot.\n\n\x20RE-ANNOUNCE,\
    \x20NOT\x20RELAY\x20STATE\x20(the\x20reason\x20there\x20is\x20no\x20serv\
    er-side\x20registry).\n\x20A\x20hand\x20raised\x20BEFORE\x20you\x20joine\
    d\x20--\x20or\x20before\x20you\x20reconnected\x20--\x20must\x20still\n\
    \x20show,\x20otherwise\x20the\x20feature\x20is\x20broken\x20in\x20the\
    \x20ordinary\x20case.\x20That\x20is\x20solved\n\x20CLIENT-SIDE:\x20a\x20\
    client\x20whose\x20own\x20hand\x20is\x20currently\x20RAISED\x20re-sends\
    \x20this\x20packet\n\x20when\x20it\x20learns\x20of\x20a\x20new\x20peer\
    \x20(PARTICIPANT_JOINED)\x20and\x20after\x20its\x20own\n\x20reconnect/re\
    -election.\x20The\x20relay\x20never\x20remembers\x20anything.\x20Wire\
    \x20contract\x20for\n\x20implementers:\n\x20\x20\x20*\x20Re-announce\x20\
    ONLY\x20when\x20`raised\x20==\x20true`.\x20`raised\x20==\x20false`\x20is\
    \x20the\x20default\n\x20\x20\x20\x20\x20state\x20of\x20every\x20particip\
    ant,\x20so\x20announcing\x20it\x20to\x20each\x20new\x20peer\x20would\x20\
    be\n\x20\x20\x20\x20\x20pure\x20O(peers)\x20waste;\x20a\x20LOWER\x20is\
    \x20broadcast\x20once,\x20as\x20a\x20real\x20transition.\n\x20\x20\x20*\
    \x20COALESCE\x20re-announces\x20across\x20a\x20join\x20wave\x20(one\x20s\
    end\x20per\x20debounce\x20window,\n\x20\x20\x20\x20\x20not\x20one\x20per\
    \x20PARTICIPANT_JOINED),\x20or\x20a\x2020-person\x20join\x20wave\x20cost\
    s\x2020\x20sends\n\x20\x20\x20\x20\x20per\x20raised\x20hand\x20and\x20wi\
    ll\x20hit\x20the\x20relay's\x20per-sender\x20rate\x20limit.\n\x20\x20\
    \x20*\x20Preserve\x20`raised_at_ms`\x20VERBATIM\x20on\x20a\x20re-announc\
    e\x20--\x20do\x20not\x20re-stamp\x20it,\n\x20\x20\x20\x20\x20or\x20the\
    \x20hand\x20appears\x20to\x20have\x20been\x20raised\x20at\x20re-announce\
    \x20time\x20and\x20the\n\x20\x20\x20\x20\x20room's\x20ordering\x20collap\
    ses\x20whenever\x20anyone\x20joins.\n\n\x20NOT\x20E2EE-sealed:\x20CLEART\
    EXT\x20even\x20when\x20E2EE_ENABLED=true,\x20mirroring\n\x20ReactionPack\
    et,\x20because\x20the\x20relay\x20must\x20read\x20the\x20inner\x20packet\
    \x20to\x20enforce\n\x20ingress\x20validation\x20(size\x20cap\x20+\x20dis\
    play_name\x20bound)\x20and\x20a\x20raised\x20hand\x20is\n\x20broadcast-p\
    ublic\x20by\x20definition.\x20Put\x20NO\x20private\x20data\x20in\x20this\
    \x20message.\n\n\x20Attribution:\x20WHO\x20is\x20anchored\x20on\x20the\
    \x20relay-stamped\x20envelope\x20session_id.\n\x20Since\x20#2124\x20(iss\
    ue\x20#2095)\x20the\x20relay\x20stamps\x20that\x20field\x20UNCONDITIONAL\
    LY\x20from\n\x20the\x20authenticated\x20session\x20on\x20the\x20single\
    \x20fan-out\x20funnel\n\x20(`chat_server::Handler<ClientMessage>`\x20->\
    \x20`stamp_wrapper_for_broadcast`),\x20so\n\x20this\x20is\x20ENFORCED,\
    \x20not\x20aspirational:\x20a\x20client\x20cannot\x20present\x20another\
    \n\x20participant's\x20session_id\x20and\x20raise\x20a\x20hand\x20on\x20\
    their\x20behalf.\x20`display_name`\x20is\n\x20a\x20COSMETIC\x20fallback\
    \x20only;\x20never\x20identity/authorization.\n\n\n\n\x03\x04\0\x01\x12\
    \x03*\x08\x17\n\xb3\x03\n\x04\x04\0\x02\0\x12\x032\x02\x12\x1a\xa5\x03\
    \x20Absolute\x20hand\x20state.\x20true\x20=\x20raised,\x20false\x20=\x20\
    lowered.\x20NOT\x20a\x20toggle.\n\n\x20proto3\x20omits\x20default\x20val\
    ues\x20on\x20the\x20wire,\x20so\x20a\x20LOWER\x20serializes\x20to\x20zer\
    o\n\x20bytes\x20for\x20this\x20field\x20--\x20which\x20also\x20means\x20\
    an\x20EMPTY\x20or\x20truncated\x20payload\n\x20parses\x20as\x20`raised\
    \x20=\x20false`.\x20That\x20degradation\x20is\x20deliberately\x20the\x20\
    SAFE\x20one:\n\x20combined\x20with\x20the\x20relay-stamped\x20envelope\
    \x20session_id,\x20the\x20worst\x20a\x20corrupt\n\x20or\x20forged\x20pay\
    load\x20can\x20do\x20is\x20lower\x20the\x20SENDER'S\x20OWN\x20hand.\n\n\
    \x0c\n\x05\x04\0\x02\0\x05\x12\x032\x02\x06\n\x0c\n\x05\x04\0\x02\0\x01\
    \x12\x032\x07\r\n\x0c\n\x05\x04\0\x02\0\x03\x12\x032\x10\x11\n\xeb\x0c\n\
    \x04\x04\0\x02\x01\x12\x03M\x02\x1a\x1a\xdd\x0c\x20Unix\x20epoch\x20mill\
    iseconds\x20(`Date.now()`)\x20at\x20which\x20the\x20sender\x20RAISED\x20\
    its\x20hand,\n\x20set\x20once\x20at\x20the\x20false->true\x20transition\
    \x20and\x20preserved\x20verbatim\x20across\x20every\n\x20re-announce.\
    \x20Meaningless\x20(send\x200)\x20when\x20`raised\x20==\x20false`.\n\n\
    \x20WHICH\x20CLOCK,\x20AND\x20WHY\x20IT\x20MATTERS:\x20this\x20is\x20the\
    \x20SENDER'S\x20WALL\x20clock,\x20not\x20a\n\x20relay\x20clock\x20and\
    \x20not\x20a\x20monotonic\x20one.\n\x20\x20\x20*\x20It\x20cannot\x20be\
    \x20relay-stamped,\x20because\x20a\x20re-announce\x20would\x20then\x20be\
    \n\x20\x20\x20\x20\x20re-stamped\x20with\x20a\x20later\x20time\x20and\
    \x20destroy\x20the\x20original\x20ordering\x20--\x20the\n\x20\x20\x20\
    \x20\x20exact\x20case\x20(late\x20joiner)\x20the\x20field\x20exists\x20t\
    o\x20serve.\n\x20\x20\x20*\x20It\x20cannot\x20be\x20a\x20per-client\x20m\
    onotonic\x20clock\x20(`performance.now()`),\n\x20\x20\x20\x20\x20because\
    \x20those\x20have\x20per-tab\x20origins\x20and\x20are\x20not\x20comparab\
    le\x20ACROSS\n\x20\x20\x20\x20\x20clients,\x20which\x20is\x20the\x20only\
    \x20comparison\x20anyone\x20makes\x20with\x20this\x20field.\n\x20So\x20c\
    ross-client\x20skew\x20is\x20real\x20and\x20unavoidable:\x20honest\x20NT\
    P-synced\x20clients\n\x20agree\x20to\x20well\x20under\x20a\x20second,\
    \x20which\x20is\x20enough\x20for\x20\"who\x20raised\x20first\"\x20in\x20\
    a\n\x20human-paced\x20queue,\x20but\x20a\x20misconfigured\x20or\x20MALIC\
    IOUS\x20client\x20can\x20claim\x20any\n\x20value\x20(0\x20=\x20\"raised\
    \x20at\x20the\x20epoch\"\x20jumps\x20the\x20queue\x20permanently).\n\n\
    \x20Consequently\x20this\x20field\x20is\x20an\x20ADVISORY\x20DISPLAY-ORD\
    ERING\x20HINT\x20ONLY,\x20in\n\x20exactly\x20the\x20same\x20trust\x20cla\
    ss\x20as\x20`display_name`:\x20never\x20authorization,\x20never\n\x20an\
    \x20input\x20to\x20who-may-speak\x20enforcement,\x20never\x20a\x20securi\
    ty\x20decision.\x20The\x20relay\n\x20deliberately\x20neither\x20validate\
    s\x20nor\x20rewrites\x20it\x20(any\x20u64\x20is\x20syntactically\n\x20va\
    lid,\x20and\x20every\x20rewrite\x20rule\x20that\x20would\x20blunt\x20the\
    \x20forgery\x20--\x20clamping\x20to\n\x20the\x20future,\x20or\x20to\x20a\
    \x20floor\x20--\x20also\x20breaks\x20legitimate\x20re-announce\x20of\x20\
    a\x20hand\n\x20raised\x20minutes\x20ago).\x20Consumers\x20MUST\x20tie-br\
    eak\x20equal\x20values\x20deterministically\n\x20on\x20the\x20envelope\
    \x20session_id\x20so\x20that\x20every\x20participant\x20renders\x20the\
    \x20SAME\x20order.\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03M\x02\x08\n\
    \x0c\n\x05\x04\0\x02\x01\x01\x12\x03M\t\x15\n\x0c\n\x05\x04\0\x02\x01\
    \x03\x12\x03M\x18\x19\n\xc2\x04\n\x04\x04\0\x02\x02\x12\x03W\x02\x19\x1a\
    \xb4\x04\x20Cosmetic\x20display-name\x20fallback\x20for\x20the\x20pre-jo\
    in\x20display-name-cache\x20race\n\x20(a\x20re-announce\x20can\x20outrun\
    \x20the\x20joiner's\x20PARTICIPANT_JOINED\x20list\x20reply).\n\x20SAME\
    \x20threat\x20model\x20and\x20cap\x20as\x20ReactionPacket.display_name:\
    \x20attacker-\n\x20controlled,\x20so\x20the\x20relay\x20bounds\x20it\x20\
    at\x20ingress\x20(<=256\x20bytes,\x20truncated\x20at\x20a\n\x20UTF-8\x20\
    char\x20boundary)\x20and\x20the\x20client\x20renders\x20it\x20as\x20ESCA\
    PED\x20text\x20with\x20its\x20own\n\x20<=64-char\x20cap.\x20Authoritativ\
    e\x20attribution\x20is\x20the\x20relay-stamped\x20envelope\n\x20session_\
    id\x20resolved\x20through\x20the\x20display-name\x20cache;\x20this\x20is\
    \x20only\x20what\x20to\n\x20show\x20while\x20that\x20cache\x20has\x20no\
    \x20entry\x20yet.\x20Optional.\n\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03W\
    \x02\x07\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03W\x08\x14\n\x0c\n\x05\x04\
    \0\x02\x02\x03\x12\x03W\x17\x18b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(RaiseHandPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
