// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `types/viewport_packet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

///  Client -> relay viewport / "desired streams" control payload.
///
///  Carried inside a PacketWrapper whose `packet_type` is VIEWPORT. The
///  sending client lists the session_ids it is currently rendering (its
///  visible viewport). The relay records this per receiver session and
///  stops forwarding VIDEO for peers that are NOT in the set, saving
///  downstream bandwidth.
///
///  Security: this list is SUBTRACT-ONLY. It can only reduce what an
///  already-authorized session receives; it never grants access. An empty
///  `session_ids` (or no VIEWPORT packet at all) means "no viewport signal"
///  and the relay forwards everything (fail-open to legacy behaviour).
///  AUDIO is NEVER filtered by this set — off-screen speakers must still be
///  heard, and keying audio off a client-supplied list would let a client
///  silence a target. This packet is consumed by the relay and never
///  re-broadcast to other peers.
// @@protoc_insertion_point(message:ViewportPacket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ViewportPacket {
    // message fields
    ///  The session_ids the sender is currently rendering (desired/visible
    ///  set). Empty = no viewport constraint.
    // @@protoc_insertion_point(field:ViewportPacket.session_ids)
    pub session_ids: ::std::vec::Vec<u64>,
    // special fields
    // @@protoc_insertion_point(special_field:ViewportPacket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ViewportPacket {
    fn default() -> &'a ViewportPacket {
        <ViewportPacket as ::protobuf::Message>::default_instance()
    }
}

impl ViewportPacket {
    pub fn new() -> ViewportPacket {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "session_ids",
            |m: &ViewportPacket| { &m.session_ids },
            |m: &mut ViewportPacket| { &mut m.session_ids },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ViewportPacket>(
            "ViewportPacket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ViewportPacket {
    const NAME: &'static str = "ViewportPacket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    is.read_repeated_packed_uint64_into(&mut self.session_ids)?;
                },
                8 => {
                    self.session_ids.push(is.read_uint64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_uint64_size(1, &self.session_ids);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_uint64(1, &self.session_ids)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ViewportPacket {
        ViewportPacket::new()
    }

    fn clear(&mut self) {
        self.session_ids.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ViewportPacket {
        static instance: ViewportPacket = ViewportPacket {
            session_ids: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ViewportPacket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ViewportPacket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ViewportPacket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ViewportPacket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1btypes/viewport_packet.proto\"1\n\x0eViewportPacket\x12\x1f\n\x0bse\
    ssion_ids\x18\x01\x20\x03(\x04R\nsessionIdsJ\xd0\x08\n\x06\x12\x04\0\0\
    \x16\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\xfd\x06\n\x02\x04\0\x12\x04\
    \x12\0\x16\x01\x1a\xf0\x06\x20Client\x20->\x20relay\x20viewport\x20/\x20\
    \"desired\x20streams\"\x20control\x20payload.\n\n\x20Carried\x20inside\
    \x20a\x20PacketWrapper\x20whose\x20`packet_type`\x20is\x20VIEWPORT.\x20T\
    he\n\x20sending\x20client\x20lists\x20the\x20session_ids\x20it\x20is\x20\
    currently\x20rendering\x20(its\n\x20visible\x20viewport).\x20The\x20rela\
    y\x20records\x20this\x20per\x20receiver\x20session\x20and\n\x20stops\x20\
    forwarding\x20VIDEO\x20for\x20peers\x20that\x20are\x20NOT\x20in\x20the\
    \x20set,\x20saving\n\x20downstream\x20bandwidth.\n\n\x20Security:\x20thi\
    s\x20list\x20is\x20SUBTRACT-ONLY.\x20It\x20can\x20only\x20reduce\x20what\
    \x20an\n\x20already-authorized\x20session\x20receives;\x20it\x20never\
    \x20grants\x20access.\x20An\x20empty\n\x20`session_ids`\x20(or\x20no\x20\
    VIEWPORT\x20packet\x20at\x20all)\x20means\x20\"no\x20viewport\x20signal\
    \"\n\x20and\x20the\x20relay\x20forwards\x20everything\x20(fail-open\x20t\
    o\x20legacy\x20behaviour).\n\x20AUDIO\x20is\x20NEVER\x20filtered\x20by\
    \x20this\x20set\x20\xe2\x80\x94\x20off-screen\x20speakers\x20must\x20sti\
    ll\x20be\n\x20heard,\x20and\x20keying\x20audio\x20off\x20a\x20client-sup\
    plied\x20list\x20would\x20let\x20a\x20client\n\x20silence\x20a\x20target\
    .\x20This\x20packet\x20is\x20consumed\x20by\x20the\x20relay\x20and\x20ne\
    ver\n\x20re-broadcast\x20to\x20other\x20peers.\n\n\n\n\x03\x04\0\x01\x12\
    \x03\x12\x08\x16\nx\n\x04\x04\0\x02\0\x12\x03\x15\x02\"\x1ak\x20The\x20s\
    ession_ids\x20the\x20sender\x20is\x20currently\x20rendering\x20(desired/\
    visible\n\x20set).\x20Empty\x20=\x20no\x20viewport\x20constraint.\n\n\
    \x0c\n\x05\x04\0\x02\0\x04\x12\x03\x15\x02\n\n\x0c\n\x05\x04\0\x02\0\x05\
    \x12\x03\x15\x0b\x11\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x15\x12\x1d\n\
    \x0c\n\x05\x04\0\x02\0\x03\x12\x03\x15\x20!b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ViewportPacket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
