fullnameOverride: "rustlemania-ui"

image:
  repository: securityunion/rustlemania-api
  pullPolicy: Always
  tag: latest

runtimeConfig:
  apiBaseUrl: "https://app.YOUR_DOMAIN_NAME"
  wsUrl: "wss://websocket.YOUR_DOMAIN_NAME"
  webTransportHost: "https://webtransport.YOUR_DOMAIN_NAME:4433"
  oauthEnabled: "false"
  e2eeEnabled: "false"
  webTransportEnabled: "true"
  usersAllowedToStream: ""
  serverElectionPeriodMs: 2000
  audioBitrateKbps: 65
  videoBitrateKbps: 1000
  screenBitrateKbps: 1000

ingress:
  enabled: true
  redirect: false
  className: nginx
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: app.YOUR_DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
          service:
            name: rustlemania-ui
            port:
              number: 80
  tls:
    - secretName: ui-tls
      hosts:
        - app.YOUR_DOMAIN_NAME
