rustlemania-webtransport:
  fullnameOverride: webtransport-ascend
  nameOverride: webtransport-ascend
  image:
    repository: hclcr.io/hcllabs/videocall-media-server
    tag: daily-2026-03-31-0954
  imagePullSecrets:
    - name: hclcr-pull-secret
  tlsSecret: webtransport-ascend-tls
  env:
    - name: RUST_LOG
      value: "warn,quinn=warn,web-transport-quinn=warn,async_nats=warn"
    - name: NATS_URL
      value: "nats-ascend:4222"
    - name: LISTEN_URL
      value: "0.0.0.0:443"
    - name: HEALTH_LISTEN_URL
      value: "0.0.0.0:444"
    - name: CERT_PATH
      value: "/certs/tls.crt"
    - name: KEY_PATH
      value: "/certs/tls.key"
    - name: REGION
      value: "ascend"
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: SERVER_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: SERVICE_TYPE
      value: "webtransport"
    - name: SERVER_STATS_INTERVAL_SECS
      value: "5"
    - name: TOKIO_WORKER_THREADS
      value: "4"
    - name: TOKIO_BLOCKING_THREADS
      value: "2"
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: jwt-secret
          key: secret
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 3500m
      memory: 6000Mi
  service:
    type: LoadBalancer
