apiVersion: v1
kind: Service
metadata:
  name: server-{{ include "metrics-api.fullname" . }}
  labels:
    {{- include "metrics-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-stats
spec:
  type: {{ .Values.serverStats.service.type }}
  ports:
    - port: {{ .Values.serverStats.service.port }}
      targetPort: {{ .Values.serverStats.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "metrics-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server-stats
