apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustlemania.fullname" . }}-api
  labels:
    {{- include "rustlemania.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080
      protocol: TCP
      name: api
  selector:
    {{- include "rustlemania.selectorLabels" . | nindent 4 }}
