apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rustlemania.fullname" . }}-ws-api
  labels:
    {{- include "rustlemania.labels" . | nindent 4 }}
spec:
  {{- if not .Values.wsApi.autoscaling.enabled }}
  replicas: {{ .Values.wsApi.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rustlemania.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.wsApi.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rustlemania.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.wsApi.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.wsApi.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "rustlemania.fullname" . }}-ws-api
          securityContext:
            {{- toYaml .Values.wsApi.securityContext | nindent 12 }}
          image: "{{ .Values.wsApi.image.repository }}:{{ .Values.wsApi.image.tag }}"
          imagePullPolicy: {{ .Values.wsApi.image.pullPolicy }}
          env:
            {{- toYaml .Values.wsApi.env | nindent 12 }}
          ports:
            - name: ws-api
              containerPort: {{ .Values.wsApi.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.wsApi.resources | nindent 12 }}
      {{- with .Values.wsApi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wsApi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wsApi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
