apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustlemania.fullname" . }}-wt-api
  labels:
    {{- include "rustlemania.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wtApi.service.type }}
  ports:
    - port: {{ .Values.wtApi.service.port }}
      targetPort: 443
      protocol: UDP
      name: wt-api
    - port: {{ .Values.wtApi.service.port }}
      targetPort: 443
      protocol: TCP
      name: wt-api-health
  selector:
    {{- include "rustlemania.selectorLabels" . | nindent 4 }}
