name: Release iOS Library

on:
  push:
    tags:
      - 'videocall-ios-v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios,aarch64-apple-darwin
      
      - name: Install cargo-lipo
        run: |
          cargo install cargo-lipo
          cargo install bindgen-cli --force --locked
      
      - name: Build iOS library
        run: |
          cd videocall-ios
          ./build_ios.sh
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            videocall-ios/VideoCallKit/Frameworks/VideoCallIOS.xcframework.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 