name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Check environment
        run: |
          echo "Runner: $(hostname)"
          whoami
          pwd
	  printenv
	  ps -aef
	  export PATH=$PATH:/home/jenking/bin
	  echo "$HOME/bin" >> $GITHUB_PATH

      - name: Check Docker
        run: docker --version

      - name: Check kubectl
        run: kubectl version --client

      - name: Check Helm
        run: helm version

      - name: Test kubectl access
        run: |
          kubectl get nodes
          kubectl get namespaces | grep preview-infra