rustlemania-websocket:
  fullnameOverride: websocket-ascend
  nameOverride: websocket-ascend
  image:
    repository: hclcr.io/hcllabs/videocall-media-server
    tag: daily-2026-03-31-0954
  imagePullSecrets:
    - name: hclcr-pull-secret
  env:
    - name: RUST_LOG
      value: "warn,quinn=warn,web-transport-quinn=warn,async_nats=warn"
    - name: ACTIX_PORT
      value: "8080"
    - name: NATS_URL
      value: "nats-ascend:4222"
    - name: REGION
      value: "ascend"
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: SERVER_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: SERVICE_TYPE
      value: "websocket"
    - name: SERVER_STATS_INTERVAL_SECS
      value: "5"
    - name: TOKIO_WORKER_THREADS
      value: "2"
    - name: TOKIO_BLOCKING_THREADS
      value: "2"
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: jwt-secret
          key: secret
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 2200m
      memory: 4000Mi
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: websocket.videocall.conceptcar7.com
        paths:
          - path: /
            pathType: Prefix
            service:
              name: websocket-ascend
              port:
                number: 8080
